=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_walker/npc_walker.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="npc_walker" type="Wlk" />
	<xs:complexType name="Wlk">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element minOccurs="0" maxOccurs="unbounded" name="walker_template" type="WlkTemplate" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WlkTemplate">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="routestep" type="RouteStep" />
		</xs:sequence>
		<xs:attribute name="route_id" type="xs:string" use="required" />
		<xs:attribute name="pool" type="xs:int" default="1" />
		<xs:attribute name="formation" type="formationType" use="optional" default="POINT" />
		<xs:attribute name="rows" type="xs:string" use="optional" />
		<xs:attribute name="loop_type" type="LoopType" use="optional" default="NORMAL"/>
	</xs:complexType>
	<xs:complexType name="RouteStep">
		<xs:attribute name="x" type="xs:float" use="required" />
		<xs:attribute name="y" type="xs:float" use="required" />
		<xs:attribute name="z" type="xs:float" use="required" />
		<xs:attribute name="rest_time" type="xs:int" use="optional" default="0" />
	</xs:complexType>
	<xs:simpleType name="formationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="POINT" />
			<xs:enumeration value="SQUARE" />
			<xs:enumeration value="CIRCLE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LoopType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE"/>
			<xs:enumeration value="NORMAL"/>
			<xs:enumeration value="WALK_BACK"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_walker/301230000_Illuminary_Obelisk.xml
<?xml version="1.0" encoding="utf-8"?>
<npc_walker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_walker.xsd">
	<walker_template route_id="idf5_u3_east_1">
		<routestep x="252.3243" y="328.5881" z="325.00922" />
		<routestep x="252.3243" y="325.01233" z="325.00378" />
		<routestep x="252.6152" y="320.7717" z="325.00378" />
		<routestep x="252.9092" y="316.5242" z="325.00378" />
		<routestep x="252.93054" y="315.76385" z="325.00378" />
		<routestep x="253.0788" y="309.97504" z="323.66492" />
		<routestep x="253.1621" y="306.72214" z="322.65472" />
		<routestep x="253.24648" y="303.42593" z="321.78174" />
		<routestep x="253.30362" y="301.19672" z="321.19254" />
		<routestep x="253.38106" y="298.17233" z="321.35153" />
	</walker_template>
	<walker_template route_id="idf5_u3_east_2">
		<routestep x="255.3635" y="328.5584" z="325.00378" />
		<routestep x="255.37334" y="324.70734" z="325.00378" />
		<routestep x="255.38478" y="320.21738" z="325.00378" />
		<routestep x="255.39601" y="315.819" z="325.00378" />
		<routestep x="255.40651" y="311.70142" z="323.9739" />
		<routestep x="255.4175" y="307.40417" z="322.83813" />
		<routestep x="255.42647" y="303.87778" z="321.90607" />
		<routestep x="255.43285" y="301.38348" z="321.24686" />
		<routestep x="255.43758" y="299.52625" z="321.23822" />
		<routestep x="255.44145" y="298.0165" z="321.41806" />
	</walker_template>
	<walker_template route_id="idf5_u3_east_3">
		<routestep x="256.6376" y="328.7015" z="325.0038" />
		<routestep x="256.6901" y="326.613" z="325.00378" />
		<routestep x="256.81244" y="321.74658" z="325.00378" />
		<routestep x="256.91885" y="316.0163" z="325.00516" />
		<routestep x="256.9671" y="310.75107" z="323.72238" />
		<routestep x="257.01855" y="306.5928" z="322.61972" />
		<routestep x="257.0697" y="302.45358" z="321.5256" />
		<routestep x="257.0929" y="300.57806" z="321.15768" />
		<routestep x="257.1171" y="298.6106" z="321.3221" />
		<routestep x="257.14032" y="296.72263" z="321.26465" />
	</walker_template>
	<walker_template route_id="idf5_u3_east_4">
		<routestep x="258.5159" y="328.5792" z="325.0038" />
		<routestep x="258.5465" y="326.4903" z="325.00378" />
		<routestep x="258.53116" y="321.57883" z="325.00378" />
		<routestep x="258.1704" y="315.97617" z="325.00986" />
		<routestep x="257.9775" y="312.99948" z="324.39407" />
		<routestep x="258.05444" y="309.53522" z="323.39746" />
		<routestep x="257.96658" y="305.43195" z="322.31036" />
		<routestep x="257.87994" y="301.33737" z="321.2363" />
		<routestep x="257.8302" y="298.98807" z="321.15527" />
		<routestep x="257.78564" y="296.88284" z="321.29468" />
	</walker_template>
	<walker_template route_id="idf5_u3_east_5">
		<routestep x="256.90997" y="326.4982" z="325.00378" />
		<routestep x="256.94186" y="323.9177" z="325.00378" />
		<routestep x="256.94186" y="321.14764" z="325.00378" />
		<routestep x="256.54144" y="315.90945" z="325.00476" />
		<routestep x="256.29825" y="312.01047" z="324.0556" />
		<routestep x="256.4147" y="304.55136" z="322.0818" />
		<routestep x="256.46448" y="301.30252" z="321.2255" />
		<routestep x="256.50244" y="298.8244" z="321.3995" />
		<routestep x="256.52908" y="297.08438" z="321.29407" />
		<routestep x="256.55243" y="295.5615" z="321.18497" />
	</walker_template>
	<walker_template route_id="idf5_u3_east_6">
		<routestep x="253.8757" y="326.501" z="325.0038" />
		<routestep x="253.9632" y="323.58658" z="325.00378" />
		<routestep x="254.06035" y="320.3518" z="325.00378" />
		<routestep x="254.17307" y="316.59854" z="325.00378" />
		<routestep x="254.19218" y="315.96188" z="325.00378" />
		<routestep x="254.36478" y="310.2122" z="323.57928" />
		<routestep x="254.5041" y="305.57358" z="322.35248" />
		<routestep x="254.63152" y="301.3287" z="321.23068" />
		<routestep x="254.71028" y="298.7052" z="321.41415" />
		<routestep x="254.76572" y="296.85938" z="321.26917" />
	</walker_template>
	<walker_template route_id="idf5_u3_hide_1">
		<routestep x="253.1755" y="252.6574" z="298.254" />
		<routestep x="247.3499" y="252.717" z="298.25397" />
		<routestep x="240.9919" y="252.78206" z="298.25397" />
		<routestep x="235.89433" y="252.83423" z="298.33267" />
		<routestep x="233.87514" y="252.85489" z="298.31143" />
		<routestep x="230.33893" y="252.89108" z="297.4328" />
		<routestep x="222.14822" y="252.97491" z="295.87787" />
		<routestep x="217.02382" y="253.02736" z="295.77374" />
	</walker_template>
	<walker_template route_id="idf5_u3_hide_2">
		<routestep x="253.1821" y="254.566" z="298.254" />
		<routestep x="247.88107" y="254.65363" z="298.25397" />
		<routestep x="241.81233" y="254.58424" z="298.25397" />
		<routestep x="236.25757" y="254.51964" z="298.25397" />
		<routestep x="233.24753" y="254.50742" z="298.1555" />
		<routestep x="229.87248" y="254.49406" z="297.31693" />
		<routestep x="224.05374" y="254.47105" z="295.87115" />
		<routestep x="221.93431" y="254.46269" z="295.9707" />
		<routestep x="216.7937" y="254.44235" z="295.7729" />
	</walker_template>
	<walker_template route_id="idf5_u3_hide_3">
		<routestep x="253.3598" y="256.368" z="298.254" />
		<routestep x="249.01544" y="256.41254" z="298.25397" />
		<routestep x="243.72415" y="256.4668" z="298.25397" />
		<routestep x="238.26042" y="256.52264" z="298.25397" />
		<routestep x="235.98889" y="256.54593" z="298.30563" />
		<routestep x="234.0842" y="256.56546" z="298.3569" />
		<routestep x="229.55504" y="256.61176" z="297.23804" />
		<routestep x="224.26997" y="256.66595" z="295.92487" />
		<routestep x="221.54216" y="256.6939" z="295.91986" />
		<routestep x="216.8484" y="256.742" z="295.77307" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_1">
		<routestep x="184.6565" y="256.3191" z="291.8364" />
		<routestep x="194.01639" y="256.27133" z="291.83636" />
		<routestep x="197.78122" y="256.2521" z="292.73795" />
		<routestep x="202.6433" y="256.22745" z="294.03677" />
		<routestep x="206.01189" y="256.21027" z="294.9368" />
		<routestep x="208.9826" y="256.19513" z="295.73392" />
		<routestep x="210.85327" y="256.18558" z="295.74582" />
		<routestep x="213.32158" y="256.17297" z="295.8374" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_2">
		<routestep x="184.6415" y="253.7202" z="291.8364" />
		<routestep x="188.63176" y="253.73666" z="291.83636" />
		<routestep x="194.3066" y="253.76007" z="291.83636" />
		<routestep x="198.22974" y="253.77628" z="292.85776" />
		<routestep x="202.1756" y="253.79257" z="293.91183" />
		<routestep x="205.97353" y="253.80826" z="294.9264" />
		<routestep x="208.93542" y="253.82043" z="295.71973" />
		<routestep x="211.25447" y="253.83003" z="296.00256" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_3">
		<routestep x="184.6134" y="253.0914" z="291.8364" />
		<routestep x="188.85114" y="253.13474" z="291.83636" />
		<routestep x="194.1179" y="253.18863" z="291.83636" />
		<routestep x="197.65045" y="253.22478" z="292.703" />
		<routestep x="202.41815" y="253.27357" z="293.97662" />
		<routestep x="206.14117" y="253.31165" z="294.97238" />
		<routestep x="209.03787" y="253.34126" z="295.7486" />
		<routestep x="211.00111" y="253.36134" z="295.75977" />
		<routestep x="212.913" y="253.38089" z="295.8685" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_4">
		<routestep x="184.7428" y="251.3166" z="291.8842" />
		<routestep x="188.82591" y="251.84206" z="291.83636" />
		<routestep x="194.42421" y="252.56255" z="291.84116" />
		<routestep x="199.23457" y="252.74498" z="293.12787" />
		<routestep x="204.49088" y="252.94691" z="294.5312" />
		<routestep x="208.75813" y="253.11081" z="295.6743" />
		<routestep x="210.73093" y="253.18657" z="295.75177" />
		<routestep x="214.00896" y="253.31248" z="295.77924" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_5">
		<routestep x="184.6134" y="253.0914" z="291.8364" />
		<routestep x="189.30807" y="253.19957" z="291.83636" />
		<routestep x="194.26057" y="253.31367" z="291.83636" />
		<routestep x="198.19331" y="253.40428" z="292.84802" />
		<routestep x="203.04529" y="253.51608" z="294.14417" />
		<routestep x="206.1826" y="253.58838" z="294.98267" />
		<routestep x="208.68016" y="253.64592" z="295.65182" />
		<routestep x="210.57013" y="253.68947" z="295.7512" />
		<routestep x="213.20422" y="253.75015" z="295.85095" />
	</walker_template>
	<walker_template route_id="idf5_u3_north_6">
		<routestep x="186.8694" y="254.673" z="291.8364" />
		<routestep x="191.81825" y="254.673" z="291.83636" />
		<routestep x="194.39966" y="254.673" z="291.83636" />
		<routestep x="198.17114" y="254.673" z="292.8421" />
		<routestep x="203.01431" y="254.673" z="294.1359" />
		<routestep x="206.26137" y="254.673" z="295.0033" />
		<routestep x="209.0" y="254.673" z="295.73495" />
		<routestep x="210.64835" y="254.673" z="295.81277" />
		<routestep x="212.86368" y="254.673" z="295.9208" />
	</walker_template>
	<walker_template route_id="idf5_u3_south_1">
		<routestep x="326.3734" y="251.2209" z="291.83636" />
		<routestep x="322.19876" y="251.38231" z="291.83636" />
		<routestep x="316.74796" y="251.86082" z="291.83636" />
		<routestep x="311.3286" y="252.03899" z="293.24417" />
		<routestep x="306.56876" y="252.19548" z="294.5159" />
		<routestep x="302.2009" y="252.33911" z="295.68704" />
		<routestep x="300.33093" y="252.40059" z="295.74582" />
		<routestep x="297.93796" y="252.47928" z="295.877" />
	</walker_template>
	<walker_template route_id="idf5_u3_south_2">
		<routestep x="326.3337" y="252.6159" z="291.83636" />
		<routestep x="322.2902" y="252.69305" z="291.83636" />
		<routestep x="318.64313" y="252.76262" z="291.83636" />
		<routestep x="316.63535" y="252.80095" z="291.83636" />
		<routestep x="313.12863" y="252.86786" z="292.76334" />
		<routestep x="310.11874" y="252.92532" z="293.56738" />
		<routestep x="307.7484" y="252.97054" z="294.2006" />
