=== dissaramdhani/Aion4.8/game-server/data/static_data/spawns/spawns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="spawns" type="SpawnsData" />

	<xs:complexType name="SpawnsData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="spawn_map" type="SpawnMap" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="unique-npc-id"><!-- a spawn entry must be unique per npc_id (see SpawnData#afterUnmarshal) -->
					<!-- entry with same npc_id may appear twice if one has custom="true" -->
					<xs:selector xpath="spawn" />
					<xs:field xpath="@npc_id" />
					<xs:field xpath="@custom" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SpawnMap">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="base_spawn" type="BaseSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rift_spawn" type="RiftSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_spawn" type="SiegeSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vortex_spawn" type="VortexSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mercenary_spawn" type="MercenarySpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ahserion_spawn" type="AhserionsFlightSpawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="map_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseSpawn">
		<xs:sequence>
			<xs:element name="occupier_template" type="BaseOccupierTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseOccupierTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="occupier" type="BaseOccupier" use="required" />
	</xs:complexType>
	<xs:complexType name="RiftSpawn">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexSpawn">
		<xs:sequence>
			<xs:element name="state_type" type="VortexStateTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexStateTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="state" type="StateType"/>
	</xs:complexType>
	<xs:complexType name="AhserionsFlightSpawn">
		<xs:sequence>
			<xs:element name="ahserion_stage_spawn" type="AhserionStageSpawnTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="faction" type="PanesterraFaction"/>
	</xs:complexType>
	<xs:complexType name="AhserionStageSpawnTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stage" type="xs:int"/>
	</xs:complexType>
	<xs:simpleType name="PanesterraFaction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BELUS"/>
			<xs:enumeration value="ASPIDA"/>
			<xs:enumeration value="ATANATOS"/>
			<xs:enumeration value="DISILLON"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="INVASION"/>
			<xs:enumeration value="PEACE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SiegeSpawn">
		<xs:sequence>
			<xs:element name="siege_race" type="SiegeRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SiegeRaceTemplate">
		<xs:sequence>
			<xs:element name="siege_mod" type="SiegeModTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="SiegeRaceType"/>
	</xs:complexType>
	<xs:complexType name="SiegeModTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mod" type="SiegeModType"/>
	</xs:complexType>
	<xs:complexType name="MercenarySpawn">
		<xs:sequence>
			<xs:element name="mercenary_race" type="MercenaryRace" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="MercenaryRace">
		<xs:sequence>
			<xs:element name="mercenary_zone" type="MercenaryZone" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>
	<xs:complexType name="MercenaryZone">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="zone" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Spawn">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="spot" type="SpawnSpotTemplate" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="pool" type="xs:int" use="optional"/>
		<xs:attribute name="respawn_time" type="xs:int"/>
		<xs:attribute name="handler" type="SpawnHandlerType"/>
		<xs:attribute name="custom" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="difficult_id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="SpawnSpotTemplate">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
		<xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="walker_id" type="xs:string"/>
		<xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="anchor" type="xs:string"/>
		<xs:attribute name="state" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="ai" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TemporarySpawn">
		<xs:attribute name="weekdays" type="WeekdayList"/>
		<xs:attribute name="spawn_time" type="xs:string"/>
		<xs:attribute name="despawn_time" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="WeekdayList">
		<xs:list itemType="Weekday" />
	</xs:simpleType>
	<xs:simpleType name="Weekday">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MONDAY"/>
			<xs:enumeration value="TUESDAY"/>
			<xs:enumeration value="WEDNESDAY"/>
			<xs:enumeration value="THURSDAY"/>
			<xs:enumeration value="FRIDAY"/>
			<xs:enumeration value="SATURDAY"/>
			<xs:enumeration value="SUNDAY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeModType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PEACE"/>
			<xs:enumeration value="SIEGE"/>
			<xs:enumeration value="LANDING"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HeadingType">
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="120"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeRaceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ELYOS"/>
			<xs:enumeration value="ASMODIANS"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SpawnHandlerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ATTACKER"/>
			<xs:enumeration value="BOSS"/>
			<xs:enumeration value="FLAG"/>
			<xs:enumeration value="GUARDIAN"/>
			<xs:enumeration value="MERCHANT"/>
			<xs:enumeration value="OUTRIDER"/>
			<xs:enumeration value="OUTRIDER_ENHANCED"/>
			<xs:enumeration value="RIFT"/>
			<xs:enumeration value="SENTINEL"/>
			<xs:enumeration value="STATIC"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/spawns/Gather/300200000_Haramel.xml
<?xml version="1.0" encoding="UTF-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300200000">
		<!-- Amethyst -->
		<spawn npc_id="400302">
			<spot x="300.717" y="429.704" z="92.14633"/>
			<spot x="256.169" y="399.106" z="90.26486"/>
			<spot x="323.971" y="415.126" z="91.16717"/>
		</spawn>
		<!-- Crystal -->
		<spawn npc_id="400303">
			<spot x="367.291" y="376.065" z="94.30297"/>
			<spot x="382.143" y="316.132" z="86.82318"/>
			<spot x="386.906" y="282.663" z="91.517334"/>
		</spawn>
		<!-- Rose Quartz -->
		<spawn npc_id="400301">
			<spot x="326.17" y="322.972" z="88.82468"/>
			<spot x="347.481" y="323.342" z="85.86539"/>
			<spot x="326.895" y="352.164" z="88.45613"/>
		</spawn>
		<!-- Silver -->
		<spawn npc_id="400101">
			<spot x="246.437" y="364.112" z="136.52193"/>
			<spot x="213.334" y="359.185" z="139.59756"/>
			<spot x="212.621" y="350.651" z="140.69937"/>
		</spawn>
		<!-- Iron -->
		<spawn npc_id="400202">
			<spot x="69.5883" y="93.2732" z="138.70984"/>
			<spot x="86.3678" y="96.1942" z="139.05595"/>
			<spot x="78.9733" y="126.446" z="139.6161"/>
			<spot x="100.602" y="113.529" z="138.9776"/>
			<spot x="93.4669" y="83.3656" z="142.6956"/>
		</spawn>
	</spawn_map>
</spawns>

=== dissaramdhani/Aion4.8/game-server/data/static_data/spawns/Npcs/Custom/GM_Isle.xml
<?xml version="1.0" encoding="UTF-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../spawns.xsd">
    <!-- 900110000_Housing_barrack -->
    <spawn_map map_id="900110000">
        <spawn npc_id="700000" respawn_time="295">
            <spot x="2637.4797" y="216.3937" z="117.79796" h="64"/>
        </spawn>
        <spawn npc_id="700079" respawn_time="295">
            <spot x="2622.3088" y="213.28381" z="117.79796" h="4"/>
        </spawn>
        <spawn npc_id="204202" respawn_time="295">
            <spot x="2622.728" y="211.1286" z="117.79796" h="3"/>
        </spawn>
        <spawn npc_id="798056" respawn_time="295">
            <spot x="2623.0854" y="209.55208" z="117.79796" h="3"/>
        </spawn>
        <spawn npc_id="798312" respawn_time="295">
            <spot x="2623.4062" y="208.04102" z="117.79796" h="3"/>
        </spawn>
        <spawn npc_id="204074" respawn_time="295">
            <spot x="2623.7776" y="206.29451" z="117.79796" h="3"/>
        </spawn>
        <spawn npc_id="830154" respawn_time="295">
            <spot x="2624.141" y="204.58481" z="117.79796" h="3"/>
        </spawn>
        <spawn npc_id="830070" respawn_time="295">
            <spot x="2639.453" y="207.48909" z="117.79796" h="63"/>
        </spawn>
        <spawn npc_id="203751" respawn_time="295">
            <spot x="2639.1643" y="209.05585" z="117.79796" h="63"/>
        </spawn>
        <spawn npc_id="203749" respawn_time="295">
            <spot x="2638.871" y="210.64604" z="117.79796" h="63"/>
        </spawn>
        <spawn npc_id="798010" respawn_time="295">
            <spot x="2638.56" y="212.33507" z="117.79796" h="63"/>
        </spawn>
        <spawn npc_id="203735" respawn_time="295">
            <spot x="2638.2097" y="214.23415" z="117.79796" h="63"/>
        </spawn>
        <spawn npc_id="700101" respawn_time="10">
            <spot x="2584.3203" y="139.9746" z="117.0" h="2"/>
            <spot x="2584.8022" y="143.65804" z="117.125" h="116"/>
            <spot x="2585.9895" y="146.96547" z="117.125" h="112"/>
        </spawn>
    </spawn_map>
</spawns>

=== dissaramdhani/Aion4.8/game-server/data/static_data/spawns/Instances/300600000_Unstable_Abyssal_Splinter.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300600000">
		<!-- Artifact of Protection -->
		<spawn npc_id="701589">
			<spot x="326.1492" y="766.9335" z="203.1832" static_id="60" />
		</spawn>
		<!-- Unstable Enos Protector -->
		<spawn npc_id="219577">
			<spot x="660.5268" y="187.8755" z="449.8903" h="100" />
		</spawn>
		<!-- Unstable Enos Watcher -->
		<spawn npc_id="219548">
			<spot x="698.4331" y="431.0002" z="462.0062" h="106" />
		</spawn>
		<!-- Unstable Holy Orkanimum -->
		<spawn npc_id="219545">
			<spot x="650.0816" y="217.2797" z="456.7426" h="12" />
			<spot x="641.2955" y="243.604" z="462.5292" h="106" />
			<spot x="641.8997" y="282.1778" z="462.8441" h="73" />
		</spawn>
		<!-- Drakan Corpse -->
		<spawn npc_id="219585">
			<spot x="648.7668" y="139.6174" z="448.1981" h="6" />
			<spot x="646.4538" y="137.3493" z="448.1777" h="106" />
			<spot x="668.5554" y="154.9271" z="448.8253" h="50" />
			<spot x="646.6642" y="156.4884" z="447.6785" h="66" />
			<spot x="654.4019" y="144.363" z="448.4239" h="66" />
			<spot x="669.1091" y="157.0472" z="448.5819" h="30" />
			<spot x="655.899" y="167.4184" z="448.2086" h="60" />
			<spot x="648.3304" y="165.896" z="448.3096" />
			<spot x="648.9009" y="160.9725" z="447.9388" h="13" />
			<spot x="657.9028" y="144.1364" z="448.7755" />
		</spawn>
		<!-- Kaluva's Unstable Spawner -->
		<spawn npc_id="219583">
			<spot x="643.9534" y="524.2017" z="423.0811" />
		</spawn>
		<!-- Kaluva's Unstable Spawner -->
		<spawn npc_id="219582">
			<spot x="663.1912" y="556.4682" z="424.2755" />
		</spawn>
		<!-- Kaluva's Unstable Spawner -->
		<spawn npc_id="219564">
			<spot x="611.1442" y="539.6695" z="423.248" />
		</spawn>
		<!-- Kaluva's Unstable Spawner -->
		<spawn npc_id="219581">
			<spot x="628.4056" y="585.4481" z="424.3175" />
		</spawn>
		<!-- Unstable Ametgolem of Guarding -->
		<spawn npc_id="219546">
			<spot x="651.1442" y="223.0291" z="458.483" h="86" />
			<spot x="644.4316" y="221.0237" z="458.5358" h="100" />
			<spot x="642.2816" y="249.2099" z="462.6751" h="93" />
			<spot x="636.8633" y="246.3414" z="462.9286" h="100" />
			<spot x="647.5186" y="286.8143" z="463.2379" h="80" />
			<spot x="641.1099" y="285.9602" z="463.0914" h="100" />
		</spawn>
		<!-- Unstable Dayshade -->
		<spawn npc_id="219578">
			<spot x="451.2862" y="692.8484" z="432.7655" h="113" />
		</spawn>
		<!-- Unstable Kaluva the Fourth -->
		<spawn npc_id="219553">
			<spot x="634.77765" y="557.0182" z="425.0" h="113" />
		</spawn>
		<!-- Unstable Pazuzu -->
		<spawn npc_id="219554">
			<spot x="669.5757" y="335.1355" z="465.8946" h="76" />
		</spawn>
		<!-- (Unstable) Abyssal Splinter Exit -->
		<spawn npc_id="730317">
			<spot x="719.756" y="161.833" z="449.343" h="40" />
		</spawn>
		<!-- Unstable Flash Lapilimo -->
		<spawn npc_id="219550">
			<spot x="808.18" y="647.51" z="454.8155" h="96" walker_id="D27F46DA44D94DF1F306CC5303FC3DA5BC9CFF68" />
			<spot x="796.89" y="617.22" z="455.28043" h="106" walker_id="934333BE62E29B8CE5903F68064329CB7822C348" />
			<spot x="756.64" y="648.51" z="445.75342" h="6" walker_id="0FA349227F68EA9E502AD2FCC8EDB0C884C4D597" />
		</spawn>
		<!-- Ancient Treasure Box -->
		<spawn npc_id="701574">
			<spot x="270.4710" y="743.9896" z="319.3749" h="106" />
			<spot x="280.9925" y="767.5568" z="287.4333" h="66" />
			<spot x="290.2162" y="729.6007" z="253.7787" h="16" />
			<spot x="306.5070" y="715.2716" z="368.3994" h="6" />
			<spot x="311.6450" y="768.0681" z="343.8409" h="106" />
			<spot x="344.2876" y="778.7310" z="397.5779" h="33" />
			<spot x="346.9677" y="742.3782" z="365.1365" />
			<spot x="347.3535" y="735.8599" z="419.6725" h="66" />
			<spot x="350.4549" y="788.7392" z="320.6760" h="106" />
			<spot x="360.1270" y="684.1302" z="390.9752" h="33" />
			<spot x="368.2921" y="771.3032" z="347.4754" />
			<spot x="389.8283" y="763.1230" z="274.2615" h="40" />
		</spawn>
		<!-- Unstable Noble Lapilima -->
		<spawn npc_id="219560">
			<spot x="807.04" y="630.01" z="454.5897" h="100" walker_id="51EE14337303BC33A670F05D1E9E836FBF87A764" />
			<spot x="762.52" y="605.41" z="461.67227" h="40" walker_id="FDA8CA3EFAC4AF61BFB3E6AB3C42F904D3393DD4" />
		</spawn>
		<!-- Unstable Enos Grappler -->
		<spawn npc_id="219547">
			<spot x="534.35" y="666.26" z="426.174" static_id="78" walker_id="8AE2C4F2BDE907BF79BB9331C19165E1F45A2B2F" />
			<spot x="565.0715" y="621.3477" z="419.6656" h="89" />
			<spot x="581.05" y="640.2924" z="419.8894" h="60" />
			<spot x="522.2446" y="666.4486" z="427.9431" h="113" />
		</spawn>
		<!-- Death Reception -->
		<spawn npc_id="282013">
			<spot x="447.2670" y="695.3739" z="433.2287" h="113" />
		</spawn>
		<!-- Unstable Noble Lapilimo -->
		<spawn npc_id="219549">
			<spot x="790.75" y="656.64" z="452.78162" walker_id="5B4EE494D9D6D1129E5F1F10C73F9A407620A987" />
			<spot x="737.50" y="645.28" z="439.23276" walker_id="7F3CB60F7B5F5659DB6D0AE7F85D32C522B8A018" />
		</spawn>
		<!-- Ranx Highmagus -->
		<spawn npc_id="281921">
			<spot x="646.0072" y="154.4628" z="447.5803" />
			<spot x="648.1384" y="147.954" z="447.6975" />
			<spot x="646.6024" y="143.1012" z="447.7108" />
			<spot x="647.2216" y="151.446" z="447.4834" h="75" />
		</spawn>
		<!-- Unstable Flash Lapilimo -->
		<spawn npc_id="219562">
			<spot x="707.61" y="619.79" z="430.36194" h="14" walker_id="5D3362983430627E52A9B1F5F376492E901D208F" />
			<spot x="756.76" y="600.93" z="462.77676" walker_id="36F2F3011475C7A48FC834581BAA573EC6A15152" />
		</spawn>
		<!-- Unstable Flash Lapilimo -->
		<spawn npc_id="219561">
			<spot x="780.35" y="651.83" z="449.6864" walker_id="0484DFAF4890199218D1972975495DDF4DAB6B3B" />
		</spawn>
		<!-- Ranx Vindicator -->
		<spawn npc_id="281920">
			<spot x="641.5420" y="151.0970" z="447.3923" h="114" />
			<spot x="641.9771" y="153.3460" z="447.5465" h="95" />
			<spot x="643.0240" y="149.7030" z="447.2498" h="36" />
			<spot x="645.9310" y="150.8680" z="447.4655" />
			<spot x="646.7925" y="146.6156" z="447.6143" h="45" />
			<spot x="648.1770" y="144.2580" z="447.8127" />
		</spawn>
		<!-- Teleportation Device -->
		<spawn npc_id="283202">
			<spot x="302.201" y="735.16" z="197.668" h="17" />
			<spot x="334.001" y="707.736" z="197.779" h="32" />
			<spot x="362.192" y="741.592" z="197.301" h="67" />
		</spawn>
	</spawn_map>
</spawns>

=== dissaramdhani/Aion4.8/game-server/data/static_data/spawns/Instances/301130000_Sauro_Supply_Base.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="301130000">
		<!-- Archmagus Sayahum -->
		<spawn npc_id="233257">
			<spot x="263.4655" y="456.98572" z="156.70569" h="90"/>
		</spawn>
		<!-- Brigade General Sheba -->
		<spawn npc_id="230858">
			<spot x="899.76935" y="889.67096" z="411.5366" h="0"/>
		</spawn>
		<!-- Chief Gunner Kurmata -->
		<spawn npc_id="230851">
			<spot x="630.62256" y="496.80316" z="202.5307" h="90"/>
		</spawn>
		<!-- Chief of Staff Moriata -->
		<spawn npc_id="230853">
			<spot x="146.14592" y="429.8655" z="150.77364"/>
		</spawn>
		<!-- Contaminated Bloodwing -->
		<spawn npc_id="233318">
			<spot x="467.9899" y="292.37143" z="160.79488"/>
			<spot x="471.72095" y="272.09576" z="166.87561"/>
			<spot x="496.081" y="302.93884" z="177.61809"/>
			<spot x="503.4583" y="290.3955" z="175.51555"/>
		</spawn>
		<!-- Crystalline Test Subject -->
		<spawn npc_id="230841">
			<spot x="466.3141" y="380.983" z="182.15321"/>
			<spot x="469.48065" y="412.49805" z="180.94296" h="82"/>
			<spot x="490.83456" y="391.81262" z="180.94296" h="82"/>
			<spot x="491.4993" y="382.67776" z="180.94296" h="27"/>
		</spawn>
		<!-- Darkblade Ovanuka -->
		<spawn npc_id="233256">
			<spot x="262.54938" y="401.03094" z="156.83209" h="30"/>
		</spawn>
		<!-- Debilitation Turret -->
		<spawn npc_id="230836">
			<spot x="625.28754" y="308.55328" z="200.38022" h="105"/>
			<spot x="654.1997" y="308.6487" z="200.38713" h="75"/>
		</spawn>
		<!-- Derakanak the Reaver -->
		<spawn npc_id="233258">
			<spot x="495.6287" y="533.7886" z="181.74464" h="90"/>
		</spawn>
		<!-- Gatekeeper Stranir -->
		<spawn npc_id="233255">
			<spot x="382.61844" y="292.23105" z="159.26079"/>
		</spawn>
		<!-- Golem Loadbearer -->
		<spawn npc_id="230844">
			<spot x="282.13544" y="327.89053" z="159.36792"/>
			<spot x="296.80286" y="328.27884" z="159.36792" h="60"/>
		</spawn>
		<!-- Guard Captain Ahuradim -->
		<spawn npc_id="230857">
			<spot x="703.7477" y="889.7424" z="411.53677" h="60"/>
		</spawn>
		<!-- Guard Captain Rohuka -->
		<spawn npc_id="230849">
			<spot x="600.34686" y="354.4385" z="202.91283"/>
		</spawn>
		<!-- Military Supply Base Flame Cannon -->
		<spawn npc_id="284453">
			<spot x="641.6695" y="495.08136" z="202.51562" h="75"/>
		</spawn>
		<!-- Protective Shield Generator -->
		<spawn npc_id="284437">
			<spot x="688.79" y="889.9065" z="411.45676"/>
		</spawn>
		<!-- Protective Shield Generator -->
		<spawn npc_id="284445">
			<spot x="709.76355" y="874.6016" z="411.33" h="45"/>
		</spawn>
		<!-- Protective Shield Generator -->
		<spawn npc_id="284446">
			<spot x="709.9149" y="904.41016" z="411.33" h="75"/>
		</spawn>
		<!-- Researcher Teselik -->
		<spawn npc_id="230850">
			<spot x="480.297" y="331.069" z="181.79274" h="30"/>
		</spawn>
		<!-- Rusted Prototype -->
		<spawn npc_id="801955">
			<spot x="490.3563" y="380.8928" z="181.98257" static_id="134"/>
			<spot x="455.2488" y="502.4285" z="181.88536" static_id="136"/>
			<spot x="431.4404" y="452.87" z="182.09003" static_id="178"/>
		</spawn>
		<!-- Sauro Larva Detonator -->
		<spawn npc_id="230839">
			<spot x="639.4159" y="229.35568" z="191.13066" h="90" random_walk="1"/>
			<spot x="641.10492" y="226.21539" z="191.13066" h="90" random_walk="1"/>
			<spot x="642.68182" y="229.11472" z="191.13066" h="90" random_walk="1"/>
		</spawn>
		<!-- Sauro Supply Base Drone -->
		<spawn npc_id="230843">
			<spot x="497.55" y="488.23" z="182.35551" h="60" walker_id="1257DA3BCA1845C22F71D62758DC9A7B730E0457"/>
		</spawn>
		<!-- Sauro Supply Base Researcher -->
		<spawn npc_id="230845">
			<spot x="463.4862" y="379.14288" z="182.15321" h="30"/>
			<spot x="494.2933" y="401.83875" z="182.13792" h="30"/>
			<spot x="497.21927" y="369.42593" z="182.14955" h="90"/>
			<spot x="497.90283" y="383.48434" z="182.14955" h="90"/>
		</spawn>
		<!-- Sheban Legion Ambusher -->
		<spawn npc_id="230792">
			<spot x="218.39" y="429.29" z="158.79059" h="90" walker_id="81A571ECA5C22C6BCC7E3F40B881DAF1B6C9983B"/>
			<spot x="293.88" y="337.73" z="159.37" h="90"/>
			<spot x="286.09" y="337.79" z="159.37" h="90"/>
			<spot x="659.46" y="245.96" z="190.875" h="90" walker_id="65CDB06A7A9CA1D6938F1A91238AA969FB2A214C"/>
		</spawn>
		<!-- Sheban Legion Ambusher -->
		<spawn npc_id="230793">
			<spot x="425.8472" y="292.9257" z="159.94757" h="90"/>
			<spot x="638.6805" y="259.4768" z="190.875"/>
		</spawn>
		<!-- Sheban Bladesman -->
		<spawn npc_id="233286">
			<spot x="890.3" y="880" z="411.46" h="15" random_walk="4"/>
			<spot x="910" y="879" z="411.46" h="50" random_walk="4"/>
			<spot x="909.7" y="899.4" z="411.46" h="75" random_walk="4"/>
			<spot x="890.2" y="899.6" z="411.46" h="105" random_walk="4"/>
		</spawn>
		<!--<spawn npc_id="233286">
		<spot x="254.9" y="429.12" z="159.32857" h="1" walker_id="F2F5D3F7AA068E5072942CA9053C8203640002E4"/>
		<spot x="254.9" y="429.12" z="159.32857" h="1" walker_id="F2F5D3F7AA068E5072942CA9053C8203640002E4"/>
		<spot x="254.9" y="429.12" z="159.32857" h="1" walker_id="F2F5D3F7AA068E5072942CA9053C8203640002E4"/>
		</spawn> -->
		<!-- Sheban Legion Ambusher -->
		<spawn npc_id="233277">
			<spot x="289.88" y="429.61" z="158.954"/>
			<spot x="479.37" y="429.74" z="182.1956" h="60" walker_id="8414C1A26D8F01E857D420CFEEA8927A47200FFF"/>
			<spot x="480.07785" y="435.25272" z="184.16982" h="30"/>
		</spawn>
		<!-- Sheban Legion Assaulter -->
		<spawn npc_id="230786">
			<spot x="301.05884" y="387.60233" z="159.24852" h="30"/>
			<spot x="622.71265" y="334.80887" z="204.16"/>
			<spot x="624.70306" y="357.2386" z="202.78787"/>
			<spot x="628.05" y="299.89" z="200.38022" h="90" walker_id="8B1F68592074C17F46A2741D9DB669FA625F9350"/>
			<spot x="630.22" y="453.4" z="202.60855" h="90" walker_id="A16D729A9689377CE14917D08E04866268AB71D3"/>
			<spot x="639.91" y="355.83" z="202.89104" h="90" walker_id="AC05D88765D559C54D289A0B0E0104E1DA03DE53"/>
			<spot x="651.36" y="299.74" z="200.38713" h="90" walker_id="7079A5F73AB255CBD4E1D0C14351F8BC6CB2F9C3"/>
			<spot x="656.5485" y="334.82687" z="204.16" h="60"/>
			<spot x="656.7276" y="386.75317" z="204.15465" h="60"/>
		</spawn>
		<!-- Sheban Legion Assaulter -->
		<spawn npc_id="230787">
			<spot x="601.25977" y="472.03192" z="191.13799" h="75"/>
			<spot x="599.04236" y="502.11124" z="191.16943" h="105"/>
			<spot x="602.89294" y="513.48047" z="191.14013" h="105"/>
			<spot x="611.90894" y="487.1522" z="202.77065" h="90"/>
		</spawn>
		<!-- Sheban Legion Beastrider -->
		<spawn npc_id="230810">
			<spot x="297.97946" y="292.20779" z="160.35104"/>
			<spot x="639.53" y="424.01" z="202.77643" h="90" walker_id="2AB13A621C1D1BD47E9B295BBCB88DC582C55000"/>
			<spot x="654.37" y="372.96" z="204.14606" h="1" walker_id="BDD2D0EDED18E059EEFE673351BF4B1741841DD9"/>
		</spawn>
		<!-- Sheban Legion Drummer -->
		<spawn npc_id="230820">
			<spot x="301.05087" y="362.48654" z="159.24051" h="30"/>
			<spot x="333.461" y="291.49805" z="159.38156"/>
			<spot x="422.50385" y="291.91162" z="159.52084"/>
			<spot x="571.49176" y="487.63068" z="191.98903"/>
		</spawn>
		<!-- Sheban Legion Bodyguard -->
		<spawn npc_id="230826">
			<spot x="442.99243" y="448.43665" z="182.09772" h="30"/>
			<spot x="443.38834" y="450.95374" z="182.37857" h="82"/>
			<spot x="453.11" y="464.24" z="182.0713" h="82" walker_id="6297C57FA88B164B4AE6100CD27350BE82C36D5A"/>
			<spot x="494.67883" y="405.60382" z="183.35124" h="30"/>
			<spot x="495.07474" y="408.12091" z="183.35124" h="82"/>
			<spot x="495.36176" y="514.1958" z="181.82288" h="30"/>
			<spot x="495.75766" y="516.71289" z="181.66089" h="82"/>
			<spot x="514.97" y="504.53" z="181.9925" h="82" walker_id="F65D48AED139919120F61B5F85BE3828D216675A"/>
			<spot x="605.75055" y="460.0632" z="191.71703" h="40"/>
			<spot x="608.29865" y="461.4866" z="191.71703" h="40"/>
		</spawn>
		<!-- Sheban Legion Gunner -->
		<spawn npc_id="230814">
			<spot x="278.71542" y="363.07172" z="159.24051" h="30"/>
			<spot x="580.53" y="486.62" z="191.18074" h="93" walker_id="A02A1C52B3179D3F17DCC65424A1B7F8CB773442"/>
			<spot x="338.29773" y="295.50653" z="159.47446"/>
			<spot x="633.78" y="492.84" z="202.5307" h="30" walker_id="8C0C4A9EDAF819ED332F578C7AECC91A38A98785"/>
			<spot x="573.90027" y="485.8027" z="191.82411"/>
			<spot x="582.139" y="456.90952" z="191.74516" h="90"/>
			<spot x="605.1631" y="486.8443" z="191.0386" h="90"/>
		</spawn>
		<!-- Sheban Legion Medic -->
		<spawn npc_id="230804">
			<spot x="601.1664" y="500.84058" z="191.13799" h="45"/>
		</spawn>
		<!-- Sheban Legion Sorcerer -->
		<spawn npc_id="230798">
			<spot x="478.44202" y="361.4509" z="182.2329" h="30"/>
			<spot x="670.4695" y="354.25208" z="203.68098" h="75"/>
		</spawn>
		<!-- Sheban Legion Scout -->
		<spawn npc_id="230830">
			<spot x="444.86887" y="449.78113" z="182.0" h="48"/>
			<spot x="497.23819" y="515.54028" z="181.84648" h="48"/>
			<spot x="606.79773" y="461.35864" z="191.71703" h="40"/>
			<spot x="617.37805" y="215.2439" z="192.46178"/>
			<spot x="657.66956" y="215.9304" z="192.37367" h="60"/>
		</spawn>
		<!-- Tamed Spaller Fighter -->
		<spawn npc_id="230838">
			<spot x="248.27574" y="429.38965" z="159.32843" random_walk="1"/>
		</spawn>
		<!-- Tamed Spaller Gatherer -->
		<spawn npc_id="230837">
			<spot x="480.03915" y="407.32013" z="182.2329" h="30"/>
		</spawn>
		<!-- Sauro Base Grave Robber -->
		<spawn npc_id="230846">
			<spot x="464.5056" y="402.036" z="182.15321" h="4"/>
		</spawn>
		<!-- Skeletal Test Subject -->
		<spawn npc_id="230842">
			<spot x="469.7816" y="387.9862" z="181.98625"/>
			<spot x="497.36731" y="387.06223" z="181.68219" h="105"/>
		</spawn>
	</spawn_map>
</spawns>
