=== dissaramdhani/Aion4.8/game-server/data/static_data/storage_expander/storage_expander.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:element name="cube_expander" type="storageExpander"/>
	<xs:element name="warehouse_expander" type="storageExpander"/>
	<xs:complexType name="storageExpander">
		<xs:sequence>
			<xs:element name="expansion_npc" type="expansionTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="expansionTemplate">
		<xs:sequence>
			<xs:element name="expand" type="expansionLevel" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ids" type="IntListType" use="required"/>
	</xs:complexType>
	<xs:complexType name="expansionLevel">
		<xs:attribute name="level" type="xs:int"/>
		<xs:attribute name="price" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/storage_expander/warehouse_expander.xml
<?xml version="1.0" encoding="UTF-8"?>
<warehouse_expander xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storage_expander.xsd">
	<expansion_npc ids="203199 203687 203749 203750 204047 204072 204073 204377 204632 204780 204800 205122 205149 205443 205447 205536 205537 205618 205619 205711 205712 205713 205714 205715 205716 205717 205718 205772 205828 205850 205879 205901 205902 205903 205904 205994 205995 205996 205997 205998 205999 260214 260216 263215 263217 263515 263517 264715 264717 266515 266517 268015 268017 269215 269217 270115 270117 271015 271017 278009 278025 278509 278525 798139 798171 798309 798310 798312 798313 798911 798965 798995 799003 799014 799027 799042 799048 799210 799263 799287 799304 799313 799331 799353 799359 800054 800307 800315 800584 800607 800640 800645 800719 800723 800744 800747 800761 800766 800777 800781 800799 800804 800852 800863 800874 800885 800896 800907 801157 801160 801163 801166 801169 801172 801175 801178 801181 801184 801187 801191 801195 801198 801201 801205 801520 801755 802079 802094 802109 802124 802139 802154 802389 802390 802399 802400 802417 802418 802555 802586 802635 802657 804145 804157 804169 804181 804207 804211 804215 804219 804223 804227 804231 804235 804239 804243 804247 804251 804255 804259 804263 804267 804271 804275 804279 804283 804287 804291 804295 804299 804303 804307 804311 804315 804319 804323 804327 804331 804335 804339 804343 804347 804351 804355 804359 804363 804367 804371 804375 804379 804383 804387 804391 804395 804399 804403 804407 804411 804415 804419 804423 804427 804431 804435 804439 804443 804447 804451 804455 804459 804693 804694 804695 804696 804967 804968 804969 804970 804971 804972 804973 805056 805057 805058 805059 805060 805061 805062 805243 805244 805251 805252 830032 830033 830116 830117 830216 830217 830218 830219 831205 831230 831381 832778 832792">
		<expand level="1" price="1200" />
		<expand level="2" price="24000" />
		<expand level="3" price="72600" />
		<expand level="4" price="181500" />
		<expand level="5" price="363000" />
	</expansion_npc>
	<expansion_npc ids="203221">
		<expand level="2" price="24000" />
		<expand level="3" price="72600" />
	</expansion_npc>
	<expansion_npc ids="810015 810016 810035 810036 810037 810038 810041 810042">
		<expand level="1" price="1200" />
		<expand level="2" price="24000" />
		<expand level="3" price="72600" />
	</expansion_npc>
</warehouse_expander>

=== dissaramdhani/Aion4.8/game-server/data/static_data/storage_expander/cube_expander.xml
<?xml version="1.0" encoding="UTF-8"?>
<cube_expander xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storage_expander.xsd">
	<!-- Poeta / Ishalgen -->
	<expansion_npc ids="798008 798037">
		<expand level="1" price="1000" />
	</expansion_npc>
	<!-- Sanctum / Pandaemonium -->
	<expansion_npc ids="798011 798012 798058 798059">
		<expand level="1" price="1000" />
		<expand level="2" price="12000" />
		<expand level="3" price="80000" />
		<expand level="4" price="180000" />
	</expansion_npc>
	<!-- Abyss, Tigraki Island -->
	<expansion_npc ids="279022">
		<expand level="5" price="360000" />
	</expansion_npc>
</cube_expander>
