=== dissaramdhani/Aion4.8/game-server/data/static_data/ai/ai.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="ai_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ai" type="Ai" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Ai">
		<xs:sequence>
			<xs:element name="summons" type="Summons" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="bombs" type="Bombs" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npcId" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="Summons">
		<xs:sequence>
			<xs:element name="percentage" type="Percentage" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Percentage">
		<xs:sequence>
			<xs:element name="summonGroup" type="SummonGroup" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
			<xs:attribute name="percent" type="xs:int" use="required"/>
			<xs:attribute name="skillId" type="xs:int"/>
			<xs:attribute name="isIndividual" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="SummonGroup">
			<xs:attribute name="npcId" type="xs:int" use="required"/>
			<xs:attribute name="x" type="xs:float"/>
			<xs:attribute name="y" type="xs:float"/>
			<xs:attribute name="z" type="xs:float"/>
			<xs:attribute name="h" type="xs:byte" default="0"/>
			<xs:attribute name="minCount" type="xs:int" default="1"/>
			<xs:attribute name="maxCount" type="xs:int"/>
			<xs:attribute name="distance" type="xs:float"/>
			<xs:attribute name="schedule" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Bombs">
		<xs:sequence>
			<xs:element name="bomb" type="BombTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BombTemplate">
		<xs:attribute name="skillId" type="xs:int" use="required"/>
		<xs:attribute name="cd" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/ai/spawn_helpers.xml
<?xml version="1.0" encoding="UTF-8"?>
<ai_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ai.xsd">
	<!-- Ragenon Souleater -->
	<ai npcId="212145">
		<summons>
			<percentage percent="50">
				<!-- Harvested Soul -->
				<summonGroup npcId="280747" minCount="2" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Captain Berus -->
	<ai npcId="212331">
		<summons>
			<percentage percent="50">
				<!-- Cursed Sailor -->
				<summonGroup npcId="280749" minCount="3" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Pitiless Graveknight -->
	<ai npcId="212346">
		<summons>
			<percentage percent="75">
				<!-- Geschphalt's Minion -->
				<summonGroup npcId="280814" distance="3"/>
			</percentage>
			<percentage percent="30">
				<!-- Geschphalt's Minion -->
				<summonGroup npcId="280814" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Lich Curser -->
	<ai npcId="214439">
		<summons>
			<percentage percent="75">
				<!-- Faithful Subordinate -->
				<summonGroup npcId="280932" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Ferocious Warg -->
	<ai npcId="217980">
		<summons>
			<percentage percent="50">
				<!-- Summoned Baby Warg -->
				<summonGroup npcId="282791" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Ferocious Warg -->
	<ai npcId="217981">
		<summons>
			<percentage percent="50">
				<!-- Summoned Baby Warg -->
				<summonGroup npcId="282791" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<!-- Raging Kraterr -->
	<ai npcId="211715">
		<summons>
			<percentage percent="90" skillId="18389">
				<summonGroup npcId="280333" minCount="2" maxCount="5" distance="10" schedule="4"/>
			</percentage>
			<percentage percent="70" skillId="18389">
				<summonGroup npcId="280333" minCount="2" maxCount="5" distance="10" schedule="4"/>
			</percentage>
			<percentage percent="40" skillId="18389">
				<summonGroup npcId="280333" minCount="2" maxCount="5" distance="10" schedule="4"/>
			</percentage>
			<percentage percent="25" skillId="18390"/>
		</summons>
	</ai>
	<!-- Spirit King Agro -->
	<ai npcId="211908">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="280771" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="30">
				<summonGroup npcId="280771" minCount="2" distance="10"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="212648">
		<summons>
			<percentage percent="50">
				<summonGroup npcId="280739" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="40">
				<summonGroup npcId="280739" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="30">
				<summonGroup npcId="280739" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="20">
				<summonGroup npcId="280739" minCount="2" distance="10"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="212874">
		<summons>
			<percentage percent="80">
				<summonGroup npcId="280472" x="2938.67" y="883.34" z="369.814" h="79"/>
				<summonGroup npcId="280469" x="2929.45" y="888.97" z="369.793" h="88"/>
				<summonGroup npcId="280472" x="2923.81" y="876.97" z="369.561" h="36"/>
				<summonGroup npcId="280472" x="2927" y="870" z="369.51" h="44"/>
			</percentage>
			<percentage percent="60">
				<summonGroup npcId="280472" x="2938.67" y="883.34" z="369.814" h="79"/>
				<summonGroup npcId="280469" x="2929.45" y="888.97" z="369.793" h="88"/>
				<summonGroup npcId="280472" x="2923.81" y="876.97" z="369.561" h="36"/>
				<summonGroup npcId="280472" x="2927" y="870" z="369.51" h="44"/>
			</percentage>
			<percentage percent="40">
				<summonGroup npcId="280469" x="2956.56" y="858.68" z="368.89" h="92"/>
				<summonGroup npcId="280472" x="2951.7" y="879.04" z="368" h="118"/>
				<summonGroup npcId="280469" x="2928.45" y="850.91" z="368.222" h="61"/>
				<summonGroup npcId="280469" x="2913.81" y="872.17" z="368.17" h="67"/>
			</percentage>
			<percentage percent="20">
				<summonGroup npcId="280469" x="2956.56" y="858.68" z="368.89" h="92"/>
				<summonGroup npcId="280472" x="2951.7" y="879.04" z="368" h="118"/>
				<summonGroup npcId="280469" x="2928.45" y="850.91" z="368.222" h="61"/>
				<summonGroup npcId="280469" x="2913.81" y="872.17" z="368.17" h="67"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="212875">
		<summons>
			<percentage percent="80">
				<summonGroup npcId="280481" minCount="4" distance="10"/>
			</percentage>
			<percentage percent="60">
				<summonGroup npcId="280481" minCount="4" distance="10"/>
			</percentage>
			<percentage percent="40">
				<summonGroup npcId="280481" minCount="4" distance="10"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="213738">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="280705" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="55">
				<summonGroup npcId="280706" minCount="2" distance="10"/>
			</percentage>
			<percentage percent="35">
				<summonGroup npcId="280707" minCount="4" distance="10"/>
			</percentage>
			<percentage percent="15">
				<summonGroup npcId="280715" distance="10"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="213780">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="280685" minCount="3" distance="2"/>
			</percentage>
			<percentage percent="50">
				<summonGroup npcId="280686" minCount="3" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214158">
		<summons>
			<percentage percent="99">
				<summonGroup npcId="296348" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214159">
		<summons>
			<percentage percent="50">
				<summonGroup npcId="296348" distance="2"/>
			</percentage>
			<percentage percent="20">
				<summonGroup npcId="296348" distance="2"/>
				<summonGroup npcId="296349" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214163">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="296347" distance="2"/>
			</percentage>
			<percentage percent="20">
				<summonGroup npcId="296347" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214668">
		<summons>
			<percentage percent="50">
				<summonGroup npcId="281053" minCount="2" distance="2"/>
			</percentage>
			<percentage percent="25">
				<summonGroup npcId="281053" minCount="2" distance="2"/>
				<summonGroup npcId="281054" minCount="2" distance="2"/>
			</percentage>
			<percentage percent="10">
				<summonGroup npcId="281054" minCount="3" distance="2"/>
				<summonGroup npcId="281053" minCount="3" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214669">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="280975" minCount="2" distance="2"/>
			</percentage>
			<percentage percent="50">
				<summonGroup npcId="281053" minCount="2" distance="2"/>
				<summonGroup npcId="281054" minCount="2" distance="2"/>
			</percentage>
			<percentage percent="25">
				<summonGroup npcId="281053" minCount="2" distance="2"/>
				<summonGroup npcId="281054" minCount="2" distance="2"/>
			</percentage>
			<percentage percent="10">
				<summonGroup npcId="281054" minCount="3" distance="2"/>
				<summonGroup npcId="281053" minCount="3" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="215480">
		<summons>
			<percentage percent="75">
				<summonGroup npcId="282006" minCount="3" distance="2"/>
			</percentage>
			<percentage percent="40">
				<summonGroup npcId="282007" distance="2"/>
			</percentage>
			<percentage percent="30">
				<summonGroup npcId="282006" minCount="4" distance="2"/>
			</percentage>
			<percentage percent="10">
				<summonGroup npcId="282006" minCount="4" distance="2"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="214843">
		<summons>
			<percentage percent="60" skillId="17456" isIndividual="true"/>
			<percentage percent="57" skillId="18376" isIndividual="true"/>
			<percentage percent="30" skillId="17530" isIndividual="true"/>
			<percentage percent="29">
				<summonGroup npcId="214832" distance="3"/>
				<summonGroup npcId="215226" distance="3"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="215070">
		<summons>
			<percentage percent="99">
				<summonGroup npcId="281327" x="762.2455" y="516.8624" z="1012.30087"/>
				<summonGroup npcId="281327" x="763.9433" y="498.5264" z="1012.30087"/>
			</percentage>
			<percentage percent="95" skillId="18552" isIndividual="true"/>
			<percentage percent="85" skillId="18552" isIndividual="true"/>
			<percentage percent="75" skillId="18552" isIndividual="true"/>
			<percentage percent="74">
				<summonGroup npcId="281327" x="736.8599" y="530.53937" z="1011.692"/>
				<summonGroup npcId="281327" x="750.1387" y="528.2361" z="1011.859"/>
				<summonGroup npcId="281327" x="736.3838" y="486.08447" z="1011.692"/>
				<summonGroup npcId="281327" x="750.47107" y="488.26205" z="1011.859"/>
			</percentage>
			<percentage percent="70" skillId="18552" isIndividual="true"/>
			<percentage percent="55" skillId="18552" isIndividual="true"/>
			<percentage percent="50" skillId="18552" isIndividual="true"/>
			<percentage percent="40" skillId="18552" isIndividual="true"/>
			<percentage percent="30" skillId="18552" isIndividual="true"/>
			<percentage percent="25" skillId="18552" isIndividual="true"/>
			<percentage percent="20" skillId="18552" isIndividual="true"/>
			<percentage percent="15" skillId="18552" isIndividual="true"/>
			<percentage percent="10" skillId="18552" isIndividual="true"/>
			<percentage percent="5" skillId="18552" isIndividual="true"/>
		</summons>
	</ai>
	<ai npcId="215078">
		<summons>
			<percentage percent="50">
				<summonGroup npcId="281253" distance="10"/>
			</percentage>
		</summons>
	</ai>
	<ai npcId="215081">
		<summons>
			<percentage percent="80" skillId="18191" isIndividual="true"/>
			<percentage percent="55" skillId="18191" isIndividual="true"/>
			<percentage percent="30" skillId="18191" isIndividual="true"/>
			<percentage percent="5" skillId="18191" isIndividual="true"/>
		</summons>
	</ai>
