=== dissaramdhani/Aion4.8/game-server/data/static_data/legion_dominion_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="global_types.xsd" />

	<xs:element name="legion_dominion_template">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="legion_dominion_location" maxOccurs="unbounded" type="LegionDominionLocation" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="LegionDominionLocation">
		<xs:sequence>
			<xs:element name="reward" type="LegionDominionReward" maxOccurs="unbounded" />
			<xs:element name="invasion_rift" type="LegionDominionInvasionRift" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:integer" />
		<xs:attribute name="race" use="required" type="Race" />
		<xs:attribute name="world_id" use="required" type="xs:integer" />
		<xs:attribute name="zone" use="required" type="xs:string" />
		<xs:attribute name="name_id" use="required" type="xs:integer" />
	</xs:complexType>
	<xs:complexType name="LegionDominionReward">
		<xs:attribute name="rank" type="xs:int" />
		<xs:attribute name="item_id" type="xs:int" />
		<xs:attribute name="count" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="LegionDominionInvasionRift">
		<xs:attribute name="key_item_id" type="xs:int" use="required" />
		<xs:attribute name="rift_id" type="xs:int" use="required" />
	</xs:complexType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/legion_dominion_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<legion_dominion_template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="legion_dominion_template.xsd">
	<legion_dominion_location id="1" world_id="220080000" zone="LegionDominionArea_01" race="ASMODIANS" name_id="404623">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000233" count="1" />
		<reward rank="1" item_id="169610352" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000233" rift_id="2289" />
	</legion_dominion_location>
	<legion_dominion_location id="2" world_id="220080000" zone="LegionDominionArea_02" race="ASMODIANS" name_id="404624">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000234" count="1" />
		<reward rank="1" item_id="169610353" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000234" rift_id="2290" />
	</legion_dominion_location>
	<legion_dominion_location id="3" world_id="220080000" zone="LegionDominionArea_03" race="ASMODIANS" name_id="404625">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000235" count="1" />
		<reward rank="1" item_id="169610354" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000235" rift_id="2291" />
	</legion_dominion_location>
	<legion_dominion_location id="4" world_id="210070000" zone="LegionDominionArea_04" race="ELYOS" name_id="404633">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000227" count="1" />
		<reward rank="1" item_id="169610349" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000227" rift_id="2189" />
	</legion_dominion_location>
	<legion_dominion_location id="5" world_id="210070000" zone="LegionDominionArea_05" race="ELYOS" name_id="404634">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000231" count="1" />
		<reward rank="1" item_id="169610350" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000231" rift_id="2190" />
	</legion_dominion_location>
	<legion_dominion_location id="6" world_id="210070000" zone="LegionDominionArea_06" race="ELYOS" name_id="404635">
		<reward rank="1" item_id="188053896" count="1" />
		<reward rank="1" item_id="185000232" count="1" />
		<reward rank="1" item_id="169610351" count="1" />
		<reward rank="2" item_id="188053896" count="1" />
		<reward rank="3" item_id="188053897" count="1" />
		<invasion_rift key_item_id="185000232" rift_id="2191" />
	</legion_dominion_location>
</legion_dominion_template>
