=== dissaramdhani/Aion4.8/game-server/data/static_data/world_raid/world_raids.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../spawns/spawns.xsd" />

	<xs:element name="world_raid_locations" type="WorldRaidLocations" />

	<xs:complexType name="WorldRaidLocations">
		<xs:sequence>
			<xs:element name="world_raid_location" type="WorldRaidLocation" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WorldRaidLocation">
		<xs:sequence>
			<xs:element name="world_raid_npcs" type="WorldRaidNpcs" />
			<xs:element name="location_markers" type="LocationMarkers" />
		</xs:sequence>
		<xs:attribute name="location_id" type="xs:int" use="required" />
		<xs:attribute name="map_id" type="xs:int" use="required" />
		<xs:attribute name="x" type="xs:float" use="required" />
		<xs:attribute name="y" type="xs:float" use="required" />
		<xs:attribute name="z" type="xs:float" use="required" />
		<xs:attribute name="h" type="HeadingType" />
	</xs:complexType>
	<xs:complexType name="LocationMarkers">
		<xs:sequence>
			<xs:element name="spot" type="MarkerSpot" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MarkerSpot">
		<xs:attribute name="x" type="xs:float" use="required" />
		<xs:attribute name="y" type="xs:float" use="required" />
		<xs:attribute name="z" type="xs:float" use="required" />
		<xs:attribute name="h" type="HeadingType" use="required" />
	</xs:complexType>
	<xs:complexType name="WorldRaidNpcs">
		<xs:sequence>
			<xs:element name="world_raid_npc" type="WorldRaidNpc" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WorldRaidNpc">
		<xs:attribute name="npc_id" type="xs:int" use="required" />
		<xs:attribute name="death_msg_id" type="death_msg_id" />
	</xs:complexType>

	<xs:simpleType name="death_msg_id" id="death_msg_id">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1402387"/>
			<xs:maxInclusive value="1402392"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/world_raid/world_raids.xml
<world_raid_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="world_raids.xsd">
	<!-- Verteron -->
	<world_raid_location location_id="1" map_id="210030000" x="1587.52" y="2078.81" z="155.85437" h="29">
		<world_raid_npcs>
			<!-- Third-rate Aitos | STR_MSG_WORLDRAID_MESSAGE_DIE_03 -->
			<world_raid_npc npc_id="234558" death_msg_id="1402389" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1615.2394" y="2072.2388" z="160.26215" h="0" />
			<spot x="1562.2804" y="2081.5738" z="156.23248" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="2" map_id="210030000" x="2484.98" y="826.09" z="100.61937" h="29">
		<world_raid_npcs>
			<!-- Third-rate Bomb Tumon | STR_MSG_WORLDRAID_MESSAGE_DIE_04 -->
			<world_raid_npc npc_id="234559" death_msg_id="1402390" />
		</world_raid_npcs>
		<location_markers>
			<spot x="2481.6819" y="799.7156" z="99.375" h="0" />
			<spot x="2503.398" y="842.7999" z="99.5" h="0" />
			<spot x="2499.7117" y="803.7157" z="99.23248" h="0" />
			<spot x="2467.6697" y="846.5846" z="99.176926" h="0" />
			<spot x="2456.4114" y="828.7191" z="98.92642" h="0" />
			<spot x="2486.8775" y="851.5188" z="99.030075" h="0" />
			<spot x="2465.0284" y="806.584" z="99.10077" h="0" />
			<spot x="2509.4249" y="824.7455" z="99.18626" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="3" map_id="210030000" x="1703.98" y="1663.38" z="102.16375" h="29">
		<world_raid_npcs>
			<!-- Third-rate Venoid | STR_MSG_WORLDRAID_MESSAGE_DIE_06 -->
			<world_raid_npc npc_id="234560" death_msg_id="1402392" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1730.2171" y="1671.1357" z="101.94258" h="0" />
			<spot x="1681.2549" y="1653.2292" z="102.42317" h="0" />
			<spot x="1719.1396" y="1685.7576" z="101.653" h="0" />
			<spot x="1694.9719" y="1638.5859" z="103.67325" h="0" />
			<spot x="1730.3749" y="1654.8886" z="102.819466" h="0" />
			<spot x="1717.2458" y="1639.574" z="105.569595" h="0" />
			<spot x="1681.0419" y="1674.1789" z="101.908554" h="0" />
			<spot x="1698.1355" y="1687.2211" z="102.82632" h="0" />
		</location_markers>
	</world_raid_location>
	<!-- Altgard -->
	<world_raid_location location_id="4" map_id="220030000" x="2893.61" y="1514.2" z="250.26312" h="28">
		<world_raid_npcs>
			<!-- Third-rate Venoid | STR_MSG_WORLDRAID_MESSAGE_DIE_06 -->
			<world_raid_npc npc_id="234561" death_msg_id="1402392" />
		</world_raid_npcs>
		<location_markers>
			<spot x="2895.3089" y="1540.4974" z="252.5075" h="0" />
			<spot x="2872.1775" y="1516.7671" z="248.8013" h="0" />
			<spot x="2913.3992" y="1533.4638" z="250.9917" h="0" />
			<spot x="2878.5706" y="1534.603" z="250.56929" h="0" />
			<spot x="2913.1229" y="1498.7153" z="248.42982" h="0" />
			<spot x="2896.6346" y="1491.6777" z="248.96034" h="0" />
			<spot x="2878.7005" y="1498.1141" z="249.375" h="0" />
			<spot x="2918.8794" y="1517.1518" z="248.82004" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="5" map_id="220030000" x="1868.05" y="1672.47" z="247.375" h="28">
		<world_raid_npcs>
			<!-- Third-rate Aitos | STR_MSG_WORLDRAID_MESSAGE_DIE_03 -->
			<world_raid_npc npc_id="234562" death_msg_id="1402389" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1882.973" y="1652.2659" z="250.43655" h="0" />
			<spot x="1849.8348" y="1683.5474" z="247.375" h="0" />
			<spot x="1881.3702" y="1696.0109" z="247.375" h="0" />
			<spot x="1895.095" y="1663.7948" z="247.30656" h="0" />
			<spot x="1861.6193" y="1697.0453" z="247.375" h="0" />
			<spot x="1895.4797" y="1683.4125" z="247.31924" h="0" />
			<spot x="1862.1142" y="1652.1398" z="247.5" h="0" />
			<spot x="1850.8582" y="1663.1283" z="247.375" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="6" map_id="220030000" x="1759.48" y="504.17" z="247.2825" h="28">
		<world_raid_npcs>
			<!-- Third-rate Bomb Tumon | STR_MSG_WORLDRAID_MESSAGE_DIE_04 -->
			<world_raid_npc npc_id="234563" death_msg_id="1402390" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1764.3008" y="529.6722" z="247.5" h="0" />
			<spot x="1779.0237" y="523.5392" z="247.5" h="0" />
			<spot x="1741.6318" y="491.4524" z="247.43224" h="0" />
			<spot x="1762.0241" y="481.9865" z="247.5" h="0" />
			<spot x="1737.5879" y="506.6582" z="247.5" h="0" />
			<spot x="1777.97" y="487.6998" z="247.5" h="0" />
			<spot x="1746.9352" y="528.3666" z="247.375" h="0" />
			<spot x="1785.0666" y="508.2494" z="247.5" h="0" />
		</location_markers>
	</world_raid_location>
	<!-- Eltnen -->
	<world_raid_location location_id="7" map_id="210020000" x="256.04" y="2135.38" z="207.375" h="28">
		<world_raid_npcs>
			<!-- Second-rate Tarantum | STR_MSG_WORLDRAID_MESSAGE_DIE_02 -->
			<world_raid_npc npc_id="234564" death_msg_id="1402388" />
		</world_raid_npcs>
		<location_markers>
			<spot x="278.2917" y="2135.9305" z="207.375" h="0" />
			<spot x="252.0908" y="2160.4368" z="207.4296" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="8" map_id="210020000" x="859.62" y="1151.2" z="278.39874" h="28">
		<world_raid_npcs>
			<!-- Third-rate Tarantum | STR_MSG_WORLDRAID_MESSAGE_DIE_02 -->
			<world_raid_npc npc_id="234565" death_msg_id="1402388" />
		</world_raid_npcs>
		<location_markers>
			<spot x="855.4946" y="1176.1031" z="278.7816" h="0" />
			<spot x="831.6056" y="1151.3113" z="279.17432" h="0" />
			<spot x="875.7004" y="1134.0505" z="277.01874" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="9" map_id="210020000" x="1519.67" y="1911.02" z="289.54062" h="28">
		<world_raid_npcs>
			<!-- Third-rate Aitos | STR_MSG_WORLDRAID_MESSAGE_DIE_03 -->
			<world_raid_npc npc_id="234566" death_msg_id="1402389" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1516.7855" y="1935.2955" z="287.38208" h="0" />
			<spot x="1492.2129" y="1912.2717" z="290.43942" h="0" />
			<spot x="1517.7157" y="1886.9362" z="291.71722" h="0" />
			<spot x="1540.7342" y="1911.2763" z="288.99933" h="0" />
			<spot x="1536.6033" y="1926.3564" z="287.98276" h="0" />
			<spot x="1500.9738" y="1893.0842" z="293.78946" h="0" />
			<spot x="1500.2475" y="1930.4201" z="288.45828" h="0" />
		</location_markers>
	</world_raid_location>
	<!-- Morheim -->
	<world_raid_location location_id="10" map_id="220020000" x="575.64" y="361.32" z="484.0" h="26">
		<world_raid_npcs>
			<!-- Second-rate Tarantum | STR_MSG_WORLDRAID_MESSAGE_DIE_02 -->
			<world_raid_npc npc_id="234567" death_msg_id="1402388" />
		</world_raid_npcs>
		<location_markers>
			<spot x="566.0052" y="383.6514" z="480.35287" h="0" />
			<spot x="598.9109" y="368.5279" z="482.19516" h="0" />
			<spot x="599.2761" y="356.0549" z="483.33707" h="0" />
			<spot x="565.6821" y="339.8286" z="484.62164" h="0" />
			<spot x="583.2932" y="339.7141" z="485.9812" h="0" />
			<spot x="585.343" y="383.8465" z="480.6583" h="0" />
			<spot x="553.9524" y="351.6968" z="479.66696" h="0" />
			<spot x="553.0511" y="370.4681" z="478.13058" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="11" map_id="220020000" x="401.12" y="1722.09" z="441.11377" h="26">
		<world_raid_npcs>
			<!-- Third-rate Aitos | STR_MSG_WORLDRAID_MESSAGE_DIE_03 -->
			<world_raid_npc npc_id="234568" death_msg_id="1402389" />
		</world_raid_npcs>
		<location_markers>
			<spot x="410.8052" y="1700.493" z="442.18192" h="0" />
			<spot x="379.4131" y="1711.1492" z="441.85635" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="12" map_id="220020000" x="1050.08" y="1247.85" z="252.59625" h="26">
		<world_raid_npcs>
			<!-- Second-rate Tarantum | STR_MSG_WORLDRAID_MESSAGE_DIE_02 -->
			<world_raid_npc npc_id="234569" death_msg_id="1402388" />
		</world_raid_npcs>
		<location_markers />
	</world_raid_location>
	<!-- Theobomos -->
	<world_raid_location location_id="13" map_id="210060000" x="2429.27" y="2619.89" z="40.25" h="27">
		<world_raid_npcs>
			<!-- Second-rate Magnorion | STR_MSG_WORLDRAID_MESSAGE_DIE_01 -->
			<world_raid_npc npc_id="234570" death_msg_id="1402387" />
		</world_raid_npcs>
		<location_markers>
			<spot x="2430.3885" y="2591.3167" z="42.109695" h="0" />
			<spot x="2446.9571" y="2640.2066" z="44.44989" h="0" />
			<spot x="2456.5611" y="2620.1917" z="45.359344" h="0" />
			<spot x="2448.1678" y="2599.2889" z="43.565414" h="0" />
			<spot x="2401.7378" y="2620.2901" z="40.034515" h="0" />
			<spot x="2411.2046" y="2640.6104" z="42.126007" h="0" />
			<spot x="2409.4856" y="2600.033" z="39.84285" h="0" />
			<spot x="2430.0896" y="2647.47" z="41.7612" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="14" map_id="210060000" x="1771.8" y="1356.03" z="18.125" h="27">
		<world_raid_npcs>
			<!-- Third-rate Aitos | STR_MSG_WORLDRAID_MESSAGE_DIE_03 -->
			<world_raid_npc npc_id="234571" death_msg_id="1402389" />
		</world_raid_npcs>
		<location_markers>
			<spot x="1744.2679" y="1356.4266" z="18.733253" h="0" />
			<spot x="1772.9185" y="1327.4532" z="20.761688" h="0" />
			<spot x="1790.6978" y="1335.4253" z="19.196838" h="0" />
			<spot x="1752.0157" y="1336.1695" z="20.101837" h="0" />
			<spot x="1799.0911" y="1356.3282" z="17.943192" h="0" />
			<spot x="1789.4871" y="1376.3431" z="18.428505" h="0" />
			<spot x="1753.7347" y="1376.7469" z="20.126526" h="0" />
			<spot x="1772.6197" y="1383.6065" z="19.200806" h="0" />
		</location_markers>
	</world_raid_location>
	<world_raid_location location_id="15" map_id="210060000" x="556.65" y="2232.53" z="44.125" h="27">
		<world_raid_npcs>
			<!-- Third-rate Venoid | STR_MSG_WORLDRAID_MESSAGE_DIE_06 -->
			<world_raid_npc npc_id="234572" death_msg_id="1402392" />
		</world_raid_npcs>
		<location_markers>
			<spot x="538.5178" y="2253.2461" z="43.95288" h="0" />
		</location_markers>
	</world_raid_location>
