=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/npc_skills.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:element name="npc_skill_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="npc_skills" type="NpcSkillList" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NpcSkillList">
		<xs:sequence>
			<xs:element name="npc_skill" type="NpcSkillTemplate" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="npc_ids" type="IntListType" />
	</xs:complexType>
	<xs:complexType name="NpcSkillTemplate">
		<xs:sequence>
			<xs:element name="cond" type="NpcSkillConditionTemplate" minOccurs="0" />
			<xs:element name="spawn_npc" type="NpcSkillSpawn" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="lv" type="xs:int" />
		<xs:attribute name="prob" type="xs:int" />
		<xs:attribute name="max_hp" type="xs:int" default="100" />
		<xs:attribute name="min_hp" type="xs:int" />
		<xs:attribute name="max_time" type="xs:int" />
		<xs:attribute name="min_time" type="xs:int" />
		<xs:attribute name="conjunction" type="ConjunctionType" />
		<xs:attribute name="cd" type="xs:int" />
		<xs:attribute name="is_post_spawn" type="xs:boolean" />
		<xs:attribute name="prio" type="xs:int" />
		<xs:attribute name="next_skill_time" type="xs:int" />
		<xs:attribute name="next_chain_id" type="xs:int" />
		<xs:attribute name="chain_id" type="xs:int" />
		<xs:attribute name="max_chain_time" type="xs:int" />
		<xs:attribute name="target" type="NpcSkillTargetAttribute" />
	</xs:complexType>
	<xs:complexType name="NpcSkillConditionTemplate">
		<xs:attribute name="cond_type" type="ConditionType" />
		<xs:attribute name="range" type="xs:int" />
		<xs:attribute name="hp_below" type="xs:int" />
		<xs:attribute name="skill_id" type="xs:int" />
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="despawn_time" type="xs:int" />
		<xs:attribute name="can_die" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="NpcSkillSpawn">
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="min_distance" type="xs:int" />
		<xs:attribute name="max_distance" type="xs:int" />
		<xs:attribute name="min_count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" />
	</xs:complexType>
	<xs:simpleType name="ConjunctionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AND" />
			<xs:enumeration value="OR" />
			<xs:enumeration value="XOR" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConditionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HELP_FRIEND" />
			<xs:enumeration value="TARGET_IS_IN_ANY_STUN" />
			<xs:enumeration value="TARGET_IS_IN_RANGE" />
			<xs:enumeration value="TARGET_IS_IN_STUMBLE" />
			<xs:enumeration value="TARGET_IS_STUNNED" />
			<xs:enumeration value="TARGET_IS_SLEEPING" />
			<xs:enumeration value="TARGET_IS_AETHERS_HOLD" />
			<xs:enumeration value="TARGET_IS_POISONED" />
			<xs:enumeration value="TARGET_IS_BLEEDING" />
			<xs:enumeration value="TARGET_IS_FLYING" />
			<xs:enumeration value="TARGET_IS_GATE" />
			<xs:enumeration value="TARGET_IS_PLAYER" />
			<xs:enumeration value="TARGET_IS_NPC" />
			<xs:enumeration value="TARGET_IS_PHYSICAL_CLASS" />
			<xs:enumeration value="TARGET_IS_MAGICAL_CLASS" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_II" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_III" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_IV" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_V" />
			<xs:enumeration value="SELECT_TARGET_AFFECTED_BY_SKILL" />
			<xs:enumeration value="NPC_IS_ALIVE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NpcSkillTargetAttribute">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FRIEND" />
			<xs:enumeration value="ME" />
			<xs:enumeration value="MOST_HATED" />
			<xs:enumeration value="SECOND_MOST_HATED" />
			<xs:enumeration value="THIRD_MOST_HATED" />
			<xs:enumeration value="RANDOM" />
			<xs:enumeration value="RANDOM_EXCEPT_MOST_HATED" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/open_worlds/220070000_Gelkmaros.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_skills.xsd">
    <npc_skills npc_ids="216580">
        <npc_skill id="18722" lv="1" prob="100" min_time="30000" cd="120000" prio="2" /><!-- Primal Fear -->
        <npc_skill id="20100" lv="1" prob="100" min_time="180000" cd="64000" prio="1" /><!-- Padmarashka' Roar -->
        <npc_skill id="20093" lv="6" prob="70" cd="26000" /><!-- Destructive Claw -->
        <npc_skill id="20401" lv="6" prob="70" cd="26000" /><!-- Venomous Claw -->
        <npc_skill id="20098" lv="8" prob="60" max_hp="80" cd="15000" /><!-- Brandish Tail -->
        <npc_skill id="20094" lv="7" prob="60" max_hp="70" cd="15000" /><!-- Destructive Bite -->
        <npc_skill id="18724" lv="9" prob="80" max_hp="60" cd="26000" /><!-- Poisonous Breath -->
        <npc_skill id="19183" lv="1" prob="80" max_hp="50" cd="30000" /><!-- Chilling Shriek -->
        <npc_skill id="20096" lv="24" prob="70" max_hp="40" next_chain_id="1" next_skill_time="2000" target="ME" /><!-- Barrier of Deadly Poison -->
        <npc_skill id="19185" lv="1" prob="100" chain_id="1" /><!-- Toxic Miasma -->
        <npc_skill id="20097" lv="39" prob="100" max_hp="30" cd="30000" /><!-- Whirlpool of Death -->
    </npc_skills>
    <!-- Naduka Blade Captain -->
    <npc_skills npc_ids="281938">
        <npc_skill id="19162" lv="1" prob="100" />
        <npc_skill id="19163" lv="1" prob="100" />
    </npc_skills>
    <!-- Naduka Tribunus -->
    <npc_skills npc_ids="281939">
        <npc_skill id="19164" lv="48" prob="100" />
        <npc_skill id="19165" lv="48" prob="100" />
    </npc_skills>
    <!-- Naduka Cryptomancer -->
    <npc_skills npc_ids="281940">
        <npc_skill id="19166" lv="48" prob="100" />
        <npc_skill id="19167" lv="48" prob="100" />
    </npc_skills>
    <!-- Naduka Blade Greatpriest -->
    <npc_skills npc_ids="281941">
        <npc_skill id="19168" lv="48" prob="65" />
        <npc_skill id="19169" lv="48" prob="65" />
        <npc_skill id="17363" lv="48" prob="100" max_hp="30" cd="100000" />
    </npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/300700000_The_Hexway.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<npc_skills npc_ids="219600"><!-- Laksyaka Legatus -->
		<npc_skill id="18166" lv="50" prob="18" />
		<npc_skill id="16785" lv="50" prob="36" />
		<npc_skill id="18164" lv="50" prob="9" />
		<npc_skill id="16608" lv="50" prob="9" />
		<npc_skill id="16519" lv="50" prob="27" />
	</npc_skills>
	<npc_skills npc_ids="219601"><!-- Laksyaka Magus -->
		<npc_skill id="18174" lv="50" prob="36" />
		<npc_skill id="17039" lv="50" prob="18" />
		<npc_skill id="16775" lv="50" prob="27" />
		<npc_skill id="18157" lv="50" prob="9" />
		<npc_skill id="18175" lv="50" prob="9" />
	</npc_skills>
	<npc_skills npc_ids="219602"><!-- Laksyaka Ambusher -->
		<npc_skill id="16608" lv="50" prob="18" />
		<npc_skill id="16540" lv="50" prob="18" />
		<npc_skill id="17934" lv="50" prob="18" />
		<npc_skill id="18159" lv="50" prob="29" />
		<npc_skill id="18158" lv="50" prob="12" />
		<npc_skill id="19125" lv="50" prob="6" />
	</npc_skills>
	<npc_skills npc_ids="219603"><!-- Laksyaka Sniper -->
		<npc_skill id="18173" lv="50" prob="25" />
		<npc_skill id="17003" lv="50" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219604"><!-- Laksyaka Officer -->
		<npc_skill id="17008" lv="50" prob="21" />
		<npc_skill id="16566" lv="50" prob="25" />
		<npc_skill id="16563" lv="50" prob="24" />
		<npc_skill id="16638" lv="50" prob="14" />
		<npc_skill id="16565" lv="50" prob="4" />
		<npc_skill id="16837" lv="50" prob="4" />
	</npc_skills>
	<npc_skills npc_ids="219605"><!-- Laksyaka Infantry -->
		<npc_skill id="17475" lv="54" prob="25" />
		<npc_skill id="17465" lv="54" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219606"><!-- Laksyaka Bladesworn -->
		<npc_skill id="17420" lv="54" prob="25" />
		<npc_skill id="17408" lv="54" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219607"><!-- Laksyaka Sentry -->
		<npc_skill id="17492" lv="54" prob="33" />
		<npc_skill id="17489" lv="54" prob="50" />
		<npc_skill id="17490" lv="54" prob="17" />
	</npc_skills>
	<npc_skills npc_ids="219608"><!-- Laksyaka Elite Medic -->
		<npc_skill id="17480" lv="54" prob="29" />
		<npc_skill id="16635" lv="54" prob="14" />
		<npc_skill id="17487" lv="54" prob="21" />
		<npc_skill id="17486" lv="54" prob="14" />
		<npc_skill id="16563" lv="54" prob="7" />
		<npc_skill id="17497" lv="54" prob="7" />
		<npc_skill id="17485" lv="54" prob="7" />
	</npc_skills>
	<npc_skills npc_ids="219609"><!-- Captain Jarka -->
		<npc_skill id="18166" lv="54" prob="29" />
		<npc_skill id="16608" lv="54" prob="29" />
		<npc_skill id="16519" lv="54" prob="29" />
		<npc_skill id="18165" lv="54" prob="14" />
	</npc_skills>
	<npc_skills npc_ids="286933 219610"><!-- Captain Lakhara (B3), Adjutant Galamat (B5) -->
		<npc_skill id="16608" lv="65" prob="75" cd="15000" />
		<npc_skill id="17497" lv="65" prob="75" cd="20000" />
		<npc_skill id="17485" lv="65" prob="50" cd="35000" />
		<npc_skill id="17039" lv="65" prob="30" cd="5000" next_skill_time="3000" target="RANDOM_EXCEPT_MOST_HATED" />
		<npc_skill id="17480" lv="65" prob="60" cd="30000" target="RANDOM" />
	</npc_skills>
	<npc_skills npc_ids="219611 219614"><!-- Laksyaka Bladesworn (B1), Laksyaka Infantry (B6) -->
		<npc_skill id="17480" lv="65" prob="75" cd="6000" target="RANDOM_EXCEPT_MOST_HATED" />
		<npc_skill id="17497" lv="65" prob="75" cd="15000" />
		<npc_skill id="18164" lv="65" prob="75" cd="10000" target="MOST_HATED" />
		<npc_skill id="18174" lv="65" prob="100" cd="20000" max_time="50000" min_time="30000" />
	</npc_skills>
	<npc_skills npc_ids="219612 219613"><!-- Laksyaka Infantry (B3), Laksyaka Infantry(B4) -->
		<npc_skill id="17480" lv="65" prob="75" cd="6000" target="RANDOM_EXCEPT_MOST_HATED" />
		<npc_skill id="17497" lv="65" prob="75" cd="15000" />
		<npc_skill id="18164" lv="65" prob="75" cd="10000" target="MOST_HATED" />
		<npc_skill id="18174" lv="65" prob="100" cd="20000" max_time="50000" min_time="30000" />
	</npc_skills>
	<npc_skills npc_ids="219634"><!-- Laksyaka Legatus -->
		<npc_skill id="18166" lv="50" prob="30" />
		<npc_skill id="16785" lv="50" prob="40" />
		<npc_skill id="18164" lv="50" prob="20" />
		<npc_skill id="16608" lv="50" prob="10" />
	</npc_skills>
	<npc_skills npc_ids="219635"><!-- Laksyaka Magus -->
		<npc_skill id="18174" lv="50" prob="20" />
		<npc_skill id="16775" lv="50" prob="20" />
		<npc_skill id="17039" lv="50" prob="20" />
		<npc_skill id="16570" lv="50" prob="40" />
	</npc_skills>
	<npc_skills npc_ids="219637"><!-- Laksyaka Sniper -->
		<npc_skill id="18173" lv="50" prob="30" />
		<npc_skill id="16812" lv="50" prob="26" />
		<npc_skill id="16815" lv="50" prob="9" />
		<npc_skill id="17003" lv="50" prob="17" />
		<npc_skill id="16674" lv="50" prob="9" />
		<npc_skill id="18178" lv="50" prob="4" />
		<npc_skill id="16543" lv="50" prob="4" />
	</npc_skills>
	<npc_skills npc_ids="219638"><!-- Laksyaka Officer -->
		<npc_skill id="17008" lv="50" prob="21" />
		<npc_skill id="16566" lv="50" prob="25" />
		<npc_skill id="16563" lv="50" prob="32" />
		<npc_skill id="16638" lv="50" prob="14" />
		<npc_skill id="16565" lv="50" prob="4" />
		<npc_skill id="16837" lv="50" prob="4" />
	</npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/300560000_Shugo_Imperial_Tomb.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Strong Kobold Worker -->
	<npc_skills npc_ids="219514">
		<npc_skill id="21133" lv="1" max_hp="50" prob="0" /><!-- Binding Blow -->
	</npc_skills>
	<!-- Powerful Kobold Foreman -->
	<npc_skills npc_ids="219515">
		<npc_skill id="21132" lv="1" max_hp="90" prob="0" /><!-- Frozen Blow -->
		<npc_skill id="21131" lv="1" max_hp="30" prob="0" /><!-- Concussion Blow -->
	</npc_skills>
	<!-- Elite Krall Lookout -->
	<npc_skills npc_ids="219522">
		<npc_skill id="21133" lv="1" max_hp="50" prob="0" /><!-- Binding Blow -->
	</npc_skills>
	<!-- Elite Krall Lookout Leader -->
	<npc_skills npc_ids="219523">
		<npc_skill id="21131" lv="1" max_hp="90" prob="0" /><!-- Concussion Blow -->
		<npc_skill id="21131" lv="1" max_hp="50" prob="0" /><!-- Concussion Blow -->
		<npc_skill id="21131" lv="1" max_hp="10" prob="0" /><!-- Concussion Blow -->
	</npc_skills>
	<!-- Letu Erezat -->
	<npc_skills npc_ids="219530">
		<npc_skill id="21133" lv="1" max_hp="50" prob="0" /><!-- Binding Blow -->
	</npc_skills>
	<!-- Captain Lediar -->
	<npc_skills npc_ids="219531">
		<npc_skill id="21134" lv="1" max_hp="90" prob="0" /><!-- Flames of Madness -->
		<npc_skill id="21266" lv="1" max_hp="70" prob="0" /><!-- Summon Elite Grave Robber -->
		<npc_skill id="21134" lv="1" max_hp="50" prob="0" /><!-- Flames of Madness -->
		<npc_skill id="21134" lv="1" max_hp="20" prob="0" /><!-- Flames of Madness -->
	</npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/guard_skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_skills.xsd">
	<!-- Fighter (GFI_) -->
	<npc_skills npc_ids="235617 235618 236674">
		<npc_skill id="17059" lv="65" prob="40" cd="30000" /><!-- Cleave -->
		<npc_skill id="17061" lv="65" prob="60" cd="20000" /><!-- Force Cleave -->
		<npc_skill id="17062" lv="65" prob="60" cd="25000" /><!-- Crippling Cut -->
		<npc_skill id="17066" lv="65" prob="60" cd="35000" /><!-- Wide Aerial Lockdown -->
		<npc_skill id="17072" lv="65" prob="60" cd="15000" /><!-- Ferocious Strike -->
		<npc_skill id="17074" lv="65" prob="60" cd="30000" /><!-- Wide Area Thrust -->
		<npc_skill id="17080" lv="65" prob="60" cd="50000" /><!-- Decrease Attack -->
	</npc_skills>
	<!-- Ranger (GRA_) -->
	<!-- Witch (GWI_) -->
	<!-- Priest (GPR_) -->
	<!-- Assassin (GAS_) -->
	<!-- Trap (GTRAP_) -->
	<!-- Holy Servant (GHS_) -->
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/300520000_Dragon_Lords_Refuge.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Calindi Flamelord -->
	<npc_skills npc_ids="219359">
		<npc_skill id="20963" lv="60" prob="70" cd="25000" />
		<npc_skill id="20964" lv="60" prob="70" cd="25000" />
	</npc_skills>
	<!-- Calindi Flamelord HM -->
	<npc_skills npc_ids="236274">
		<npc_skill id="21889" lv="65" prob="70" cd="8000" /><!-- Fire Dragon Claw -->
		<npc_skill id="21890" lv="65" prob="70" cd="8000" /><!-- Frontal Devastation -->
		<npc_skill id="20915" lv="1" prob="100" cd="30000" max_hp="80" /><!-- Ignition -->
	</npc_skills>
	<!-- Fissurefang -->
	<npc_skills npc_ids="219365 236278">
		<npc_skill id="20105" lv="60" prob="40" cd="15000" />
		<npc_skill id="20145" lv="60" prob="70" />
		<npc_skill id="20146" lv="60" prob="40" />
		<npc_skill id="20169" lv="60" prob="40" />
	</npc_skills>
	<!-- Graviwing -->
	<npc_skills npc_ids="219366 236279">
		<npc_skill id="20105" lv="60" prob="40" cd="15000" />
		<npc_skill id="20145" lv="60" prob="70" />
		<npc_skill id="20146" lv="60" prob="40" />
		<npc_skill id="20157" lv="60" prob="40" />
	</npc_skills>
	<!-- Wrathclaw -->
	<npc_skills npc_ids="219367 236280">
		<npc_skill id="20105" lv="60" prob="40" cd="15000" />
		<npc_skill id="20145" lv="60" prob="40" />
		<npc_skill id="20146" lv="60" prob="40" />
		<npc_skill id="20165" lv="60" prob="20" max_hp="25" />
		<npc_skill id="20166" lv="60" prob="40" />
	</npc_skills>
	<!-- Petriscale -->
	<npc_skills npc_ids="219368 236281">
		<npc_skill id="20105" lv="60" prob="40" cd="15000" />
		<npc_skill id="20145" lv="60" prob="70" />
		<npc_skill id="20146" lv="60" prob="40" />
		<npc_skill id="20161" lv="60" prob="40" />
	</npc_skills>
	<!-- Divisive Creation -->
	<npc_skills npc_ids="283139">
		<npc_skill id="20985" lv="60" prob="100" cd="9000" />
		<npc_skill id="20986" lv="60" prob="100" />
	</npc_skills>
	<!-- Divisive Creation HM -->
	<npc_skills npc_ids="856042">
		<npc_skill id="21897" lv="1" prob="100" cd="9000" />
		<npc_skill id="21898" lv="1" prob="100" />
	</npc_skills>
	<!-- Sinking Sand -->
	<npc_skills npc_ids="283136">
		<npc_skill id="21896" lv="60" prob="100">
			<cond delay="1500" despawn_time="2500" />
		</npc_skill>
	</npc_skills>
	<!-- Rockslam -->
	<npc_skills npc_ids="283138">
		<npc_skill id="20968" lv="60" prob="100">
			<cond delay="1000" despawn_time="3000" />
		</npc_skill>
	</npc_skills>
	<!-- Rockslam HM -->
	<npc_skills npc_ids="856043">
		<npc_skill id="21899" lv="60" prob="100">
			<cond delay="1000" despawn_time="3000" />
		</npc_skill>
	</npc_skills>
	<!-- Infinite Pain -->
	<npc_skills npc_ids="283144">
		<npc_skill id="20969" lv="60" prob="100">
			<cond delay="500" despawn_time="3000" />
		</npc_skill>
	</npc_skills>
	<!-- Infinite Pain -->
	<npc_skills npc_ids="856049">
		<npc_skill id="21902" lv="1" prob="100">
			<cond delay="500" despawn_time="3000" />
		</npc_skill>
	</npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/301280000_Kysis_Barracks.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Kysis Duke -->
	<npc_skills npc_ids="233675 233676">
		<npc_skill id="18003" lv="1" prob="100" max_hp="25" cd="600000" target="ME">
			<spawn_npc npc_id="284978" min_distance="1" max_distance="1" min_count="1" max_count="1" />
		</npc_skill>
		<npc_skill id="18204" lv="65" prob="25" cd="10000" />
		<npc_skill id="18205" lv="65" prob="25" cd="10000" />
		<npc_skill id="18206" lv="65" prob="25" cd="10000" />
		<npc_skill id="18207" lv="65" prob="25" />
		<npc_skill id="18208" lv="65" prob="25" />
		<npc_skill id="18209" lv="65" prob="25" max_hp="50" />
		<npc_skill id="18210" lv="65" prob="25" cd="30000" />
		<npc_skill id="18211" lv="65" prob="25" max_hp="50" cd="30000" />
		<npc_skill id="18594" lv="65" prob="50" cd="30000" />
	</npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/300610000_Raksang_Ruins.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Draconute Scout -->
	<npc_skills npc_ids="236005">
		<npc_skill id="21135" lv="1" prob="100" is_post_spawn="true"/>
		<npc_skill id="19430" lv="56" prob="75"/>
		<npc_skill id="17243" lv="1" prob="33"/>
	</npc_skills>
	<!-- Draconute Combatant -->
	<npc_skills npc_ids="236006">
		<npc_skill id="21135" lv="1" prob="100" is_post_spawn="true"/>
		<npc_skill id="16516" lv="1" prob="75"/>
	</npc_skills>
	<!-- Drill Camp Assasin -->
	<npc_skills npc_ids="236007">
		<npc_skill id="21135" lv="1" prob="100" is_post_spawn="true"/>
		<npc_skill id="17322" lv="1" prob="50"/>
	</npc_skills>
	<!-- Drill Camp Guard | Classified Drill Camp Instructor -->
	<npc_skills npc_ids="236008 236084">
		<npc_skill id="21135" lv="1" prob="100" is_post_spawn="true"/>
		<npc_skill id="17294" lv="1" prob="80"/>
	</npc_skills>
	<!-- Trained Vespine -->
	<npc_skills npc_ids="236009">
		<npc_skill id="20945" lv="1" prob="25"/>
	</npc_skills>
	<!-- Trained Porgus | Trained Worg | Crumbling Skelesword | Trained Fierce Lapilima | Trained Drakie -->
	<npc_skills npc_ids="236010 236011 236012 236018 236021 236097">
		<npc_skill id="21300" lv="1" prob="40"/>
	</npc_skills>
	<!-- Withering Husk -->
	<npc_skills npc_ids="236013">
		<npc_skill id="16825" lv="1" prob="33"/>
	</npc_skills>
	<!-- Ragelich Adept -->
	<npc_skills npc_ids="236014">
		<npc_skill id="19052" lv="1" prob="14"/>
		<npc_skill id="20944" lv="36" prob="45"/>
		<npc_skill id="16830" lv="1" prob="100" max_hp="10"/>
	</npc_skills>
	<!-- Trained Clodworm -->
	<npc_skills npc_ids="236020 236096 236098">
		<npc_skill id="17558" lv="1" prob="67"/>
	</npc_skills>
	<!-- Drill Instructor Diplito -->
	<npc_skills npc_ids="236303">
		<npc_skill id="21287" lv="1" prob="100" max_hp="50" cd="30000"/>
		<npc_skill id="17335" lv="1" prob="75"/>
	</npc_skills>
	<!-- Drill Instructor Pratica -->
	<npc_skills npc_ids="236304">
		<npc_skill id="16405" lv="1" prob="100" cd="20000"/>
		<npc_skill id="21285" lv="1" prob="40"/>
		<npc_skill id="22658" lv="20" prob="33"/>
	</npc_skills>
	<!-- Drill Instructor Exico -->
	<npc_skills npc_ids="236305">
		<npc_skill id="17048" lv="1" prob="50"/>
		<!-- <npc_skill id="21432" lv="1" prob="100" max_hp="48" cd="60000"/> -->
	</npc_skills>
	<!-- Reviver Nasto -->
	<npc_skills npc_ids="236306">
		<npc_skill id="16570" lv="1" prob="66" cd="12000"/>
		<npc_skill id="22106" lv="1" prob="100" max_hp="66" cd="300000"/>
		<npc_skill id="22106" lv="1" prob="100" max_hp="33" cd="300000"/>
	</npc_skills>
	<!-- Improved Thermitron -->
	<npc_skills npc_ids="855852">
		<npc_skill id="21534" lv="1" prob="100"/>
	</npc_skills>
	<!-- Skeleton Guard -->
	<npc_skills npc_ids="855908">
		<npc_skill id="16556" lv="1" prob="25"/>
	</npc_skills>
</npc_skill_templates>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/instances/300800000_Infinity_Shard.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Hyperion -->
	<npc_skills npc_ids="231073">
		<npc_skill id="21254" is_post_spawn="true" />
		<npc_skill id="21241" lv="56" prob="65" target="RANDOM_EXCEPT_MOST_HATED" cd="120000"/>
		<npc_skill id="21241" lv="56" prob="65" cd="30000"/>
		<npc_skill id="21242" lv="56" prob="70" cd="8000" />
		<npc_skill id="21243" lv="56" prob="70" cd="8000" />
		<npc_skill id="21244" lv="56" prob="60" max_hp="80" cd="35000" />
		<npc_skill id="21245" lv="56" prob="60" min_hp="15" max_hp="75" cd="25000"/>
		<npc_skill id="21247" lv="56" prob="60" min_hp="50" max_hp="80" cd="30000"/>
		<npc_skill id="21247" lv="56" prob="50" min_hp="50" max_hp="80" cd="140000" target="RANDOM_EXCEPT_MOST_HATED" />
		<npc_skill id="21248" lv="56" prob="50" min_hp="15" max_hp="45" cd="140000" target="RANDOM_EXCEPT_MOST_HATED" />
		<npc_skill id="21248" lv="56" prob="60" min_hp="15" max_hp="45" cd="30000" />
		<npc_skill id="21249" lv="56" prob="50" max_hp="10" cd="140000" target="RANDOM_EXCEPT_MOST_HATED"/>
		<npc_skill id="21249" lv="56" prob="60" max_hp="10" cd="30000"/>
		<npc_skill id="21250" lv="56" prob="70" min_hp="30" max_hp="75" chain_id="0" next_chain_id="1" next_skill_time="0" cd="55000" prio="2"/>
		<npc_skill id="21251" lv="56" prob="100" chain_id="1" />
		<npc_skill id="21250" lv="56" prob="70" max_hp="25" chain_id="0" next_chain_id="4" next_skill_time="0" cd="55000" prio="1"/>
		<npc_skill id="21252" lv="56" prob="100" chain_id="4"/>
	</npc_skills>
	<!-- Ide Forcefield Generator -->
	<npc_skills npc_ids="231074 231078 231082 231086">
		<npc_skill id="21371" lv="41" is_post_spawn="true" />
	</npc_skills>
	<!-- Agent Kabalash -->
	<npc_skills npc_ids="231075 231087">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="20701" lv="56" is_post_spawn="true"/>
		<npc_skill id="20712" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17722" lv="56" prob="70" cd="10000"/>
		<npc_skill id="17335" lv="56" prob="70" cd="10000"/>
		<npc_skill id="20179" lv="10" prob="70" cd="15000"/> <!-- TODO change to lv="56" when new NpcStats and damage calculations are implemented -->
		<npc_skill id="21288" lv="56" prob="70" cd="10000"/>
		<npc_skill id="20711" lv="56" prob="70" cd="10000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Sniper -->
	<npc_skills npc_ids="231076 231077 231080 231088">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17106" lv="56" prob="70" cd="20000"/>
		<npc_skill id="17318" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17317" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17314" lv="56" prob="70" cd="12000"/>
		<npc_skill id="21230" lv="56" prob="60"	cd="15000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Gunner -->
	<npc_skills npc_ids="231091">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="21292" lv="56" prob="80" cd="8000"/>
		<npc_skill id="21293" lv="56" prob="70" cd="15000"/>
	</npc_skills>
	<!-- Hyperion Defense Turret -->
	<npc_skills npc_ids="231102">
		<npc_skill id="16896" lv="56" prob="70" cd="15000" />
		<npc_skill id="17003" lv="56" prob="70" cd="15000" />
		<npc_skill id="21415" lv="56" prob="70" cd="15000" />
	</npc_skills>
	<!-- Ide Pool -->
	<npc_skills npc_ids="231104">
		<npc_skill id="21356" lv="56" prob="20" />
	</npc_skills>
	<!-- summoned ancient tyrhund -->
	<npc_skills npc_ids="231103">
		<npc_skill id="21300" lv="56" prob="80" cd="15000"/>
		<npc_skill id="20947" lv="56" prob="20" cd="25000"/>
	</npc_skills>
	<!-- hyperion defense combatant -->
	<npc_skills npc_ids="231096 231099 231084">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17294" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21284" lv="56" prob="70" cd="12000"/>
	</npc_skills>
	<!-- hyperion defense scout -->
	<npc_skills npc_ids="231097 231100">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17322" lv="56" prob="70" cd="12000" next_chain_id="1" next_skill_time="0"/>
		<npc_skill id="16678" lv="56" prob="100" cd="8000" chain_id="1"/>
		<npc_skill id="17295" lv="56" prob="70" cd="8000"/>
	</npc_skills>
	<!-- hyperion defense medic -->
	<npc_skills npc_ids="231098 231101">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17359" lv="56" prob="70" cd="7000"/>
		<npc_skill id="17360" lv="56" prob="70" cd="12000"/>
		<npc_skill id="17361" lv="56" prob="100" max_hp="60" cd="15000" prio="1"/>
	</npc_skills>
	<!-- hyperion defense elite sniper -->
	<npc_skills npc_ids="231089">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17318" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17106" lv="56" prob="60" cd="20000"/>
		<npc_skill id="17317" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17314" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21230" lv="56" prob="70" cd="9000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Assassin -->
	<npc_skills npc_ids="231079 231083">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17321" lv="56" prob="80" cd="8000" chain_id="1"/>
		<npc_skill id="17332" lv="56" cd="8000" />
		<npc_skill id="21289" lv="56" prob="80" cd="10000"/>
		<npc_skill id="16452" lv="56" prob="100" cd="30000" next_chain_id="1" next_skill_time="0"/>
	</npc_skills>
	<!-- hyperion defense elite fighter -->
	<npc_skills npc_ids="231090">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17295" lv="56" prob="80" cd="10000"/>
		<npc_skill id="17294" lv="56" prob="80" cd="6000"/>
	</npc_skills>
	<!-- hyperion defense elite medic -->
	<npc_skills npc_ids="231081 231085">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17359" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21278" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17361" lv="56" prob="100" cd="15000" max_hp="60" prio="1"/>
		<npc_skill id="17700" lv="56" prob="70" cd="15000"/>
		<npc_skill id="16566" lv="56" prob="100" cd="10000" max_hp="80" prio="1"/>
	</npc_skills>
</npc_skill_templates>
