=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/npc_skills.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:element name="npc_skill_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="npc_skills" type="NpcSkillList" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NpcSkillList">
		<xs:sequence>
			<xs:element name="npc_skill" type="NpcSkillTemplate" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="npc_ids" type="IntListType" />
	</xs:complexType>
	<xs:complexType name="NpcSkillTemplate">
		<xs:sequence>
			<xs:element name="cond" type="NpcSkillConditionTemplate" minOccurs="0" />
			<xs:element name="spawn_npc" type="NpcSkillSpawn" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="lv" type="xs:int" />
		<xs:attribute name="prob" type="xs:int" />
		<xs:attribute name="max_hp" type="xs:int" default="100" />
		<xs:attribute name="min_hp" type="xs:int" />
		<xs:attribute name="max_time" type="xs:int" />
		<xs:attribute name="min_time" type="xs:int" />
		<xs:attribute name="conjunction" type="ConjunctionType" />
		<xs:attribute name="cd" type="xs:int" />
		<xs:attribute name="is_post_spawn" type="xs:boolean" />
		<xs:attribute name="prio" type="xs:int" />
		<xs:attribute name="next_skill_time" type="xs:int" />
		<xs:attribute name="next_chain_id" type="xs:int" />
		<xs:attribute name="chain_id" type="xs:int" />
		<xs:attribute name="max_chain_time" type="xs:int" />
		<xs:attribute name="target" type="NpcSkillTargetAttribute" />
	</xs:complexType>
	<xs:complexType name="NpcSkillConditionTemplate">
		<xs:attribute name="cond_type" type="ConditionType" />
		<xs:attribute name="range" type="xs:int" />
		<xs:attribute name="hp_below" type="xs:int" />
		<xs:attribute name="skill_id" type="xs:int" />
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="despawn_time" type="xs:int" />
		<xs:attribute name="can_die" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="NpcSkillSpawn">
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="min_distance" type="xs:int" />
		<xs:attribute name="max_distance" type="xs:int" />
		<xs:attribute name="min_count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" />
	</xs:complexType>
	<xs:simpleType name="ConjunctionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AND" />
			<xs:enumeration value="OR" />
			<xs:enumeration value="XOR" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConditionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HELP_FRIEND" />
			<xs:enumeration value="TARGET_IS_IN_ANY_STUN" />
			<xs:enumeration value="TARGET_IS_IN_RANGE" />
			<xs:enumeration value="TARGET_IS_IN_STUMBLE" />
			<xs:enumeration value="TARGET_IS_STUNNED" />
			<xs:enumeration value="TARGET_IS_SLEEPING" />
			<xs:enumeration value="TARGET_IS_AETHERS_HOLD" />
			<xs:enumeration value="TARGET_IS_POISONED" />
			<xs:enumeration value="TARGET_IS_BLEEDING" />
			<xs:enumeration value="TARGET_IS_FLYING" />
			<xs:enumeration value="TARGET_IS_GATE" />
			<xs:enumeration value="TARGET_IS_PLAYER" />
			<xs:enumeration value="TARGET_IS_NPC" />
			<xs:enumeration value="TARGET_IS_PHYSICAL_CLASS" />
			<xs:enumeration value="TARGET_IS_MAGICAL_CLASS" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_II" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_III" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_IV" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_V" />
			<xs:enumeration value="SELECT_TARGET_AFFECTED_BY_SKILL" />
			<xs:enumeration value="NPC_IS_ALIVE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NpcSkillTargetAttribute">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FRIEND" />
			<xs:enumeration value="ME" />
			<xs:enumeration value="MOST_HATED" />
			<xs:enumeration value="SECOND_MOST_HATED" />
			<xs:enumeration value="THIRD_MOST_HATED" />
			<xs:enumeration value="RANDOM" />
			<xs:enumeration value="RANDOM_EXCEPT_MOST_HATED" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/npc_skills/rift_guard_skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_skills.xsd">
	<!-- Chaos Guardian Generals -->
	<npc_skills npc_ids="219887 219906 219913 236035 236048 236055">
		<npc_skill id="21750" lv="65" prob="90" min_hp="35" cd="15000" /> <!-- Slash -->
		<npc_skill id="21752" lv="1" prob="70" cd="80000" next_skill_time="5000" min_hp="0" max_hp="75" /> <!-- Searing Scream -->
		<npc_skill id="21753" lv="65" prob="85" max_hp="34" cd="15000" /> <!-- Flying Blade -->
		<npc_skill id="21756" lv="65" prob="90" next_chain_id="1" next_skill_time="0" cd="90000" min_hp="0" max_hp="45" target="RANDOM_EXCEPT_MOST_HATED" /> <!-- Prime Target -->
		<npc_skill id="21757" lv="65" prob="100" chain_id="1" cd="20000" next_skill_time="5000" /> <!-- Punishing Blow -->
		<npc_skill id="21758" lv="1" prob="70" cd="85000" next_skill_time="3000" target="NONE" /> <!-- Fetters -->
		<npc_skill id="17992" lv="1" prob="30" next_chain_id="2" next_skill_time="0" cd="120000" min_hp="0" max_hp="45" /> <!-- Wide Area Aerial Thrust III -->
		<npc_skill id="17995" lv="1" prob="100" chain_id="2" next_skill_time="8000" cd="20000" target="NONE"> <!-- Wide Area Crashing Wind Strike III -->
			<cond cond_type="TARGET_IS_AETHERS_HOLD" />
		</npc_skill>
	</npc_skills>
</npc_skill_templates>
