=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/global_rules.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../npcs/npcs.xsd" />
	<xs:include schemaLocation="../world_maps.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />

	<xs:element name="global_rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_rule" type="GlobalRule" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="GlobalRule">
		<xs:all>
			<xs:element name="gd_items" type="GlobalDropItems" />
			<xs:element minOccurs="0" name="gd_worlds" type="GlobalDropWorlds" />
			<xs:element minOccurs="0" name="gd_races" type="GlobalDropRaces" />
			<xs:element minOccurs="0" name="gd_ratings" type="GlobalDropRatings" />
			<xs:element minOccurs="0" name="gd_maps" type="GlobalDropMaps" />
			<xs:element minOccurs="0" name="gd_tribes" type="GlobalDropTribes" />
			<xs:element minOccurs="0" name="gd_npcs" type="GlobalDropNpcs" />
			<xs:element minOccurs="0" name="gd_npc_names" type="GlobalDropNpcNames" />
			<xs:element minOccurs="0" name="gd_npc_groups" type="GlobalDropNpcGroups" />
			<xs:element minOccurs="0" name="gd_excluded_npcs" type="GlobalDropExcludedNpcs" />
			<xs:element minOccurs="0" name="gd_zones" type="GlobalDropZones" />
		</xs:all>
		<xs:attribute name="rule_name" type="xs:string" use="required" />
		<xs:attribute name="chance" type="xs:float" use="required" />
		<xs:attribute name="dynamic_chance" type="xs:boolean" default="false" />
		<xs:attribute name="min_diff" type="xs:int" default="-99" />
		<xs:attribute name="max_diff" type="xs:int" default="99" />
		<xs:attribute name="restriction_race" type="RestrictionRace" />
		<xs:attribute name="level_based_chance_reduction" type="xs:boolean" default="false" />
		<xs:attribute name="member_limit" type="xs:int" default="1" />
		<xs:attribute name="max_drop_rule" type="xs:int" default="1" />
	</xs:complexType>

	<xs:complexType name="GlobalDropItems">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="gd_item" type="GlobalDropItem" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropItem">
		<xs:attribute type="xs:int" name="id" use="required" />
		<xs:attribute name="min_count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" />
		<xs:attribute type="xs:float" name="chance" default="100" />
	</xs:complexType>

	<xs:complexType name="GlobalDropWorlds">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_world" type="GlobalDropWorld" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropWorld">
		<xs:attribute type="worldDropType" name="wd_type" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropRaces">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_race" type="GlobalDropRace" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropRace">
		<xs:attribute type="Race" name="race" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropRatings">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_rating" type="GlobalDropRating" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropRating">
		<xs:attribute type="NpcRating" name="rating" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropMaps">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_map" type="GlobalDropMap" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropMap">
		<xs:attribute type="xs:int" name="map_id" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropTribes">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_tribe" type="GlobalDropTribe" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropTribe">
		<xs:attribute type="TribeClass" name="tribe" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcs">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc" type="GlobalDropNpc" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropNpc">
		<xs:attribute type="xs:int" name="npc_id" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcNames">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc_name" type="GlobalDropNpcName" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcName">
		<xs:attribute type="xs:string" name="value" use="required" />
		<xs:attribute type="StringFunction" name="function" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropExcludedNpcs">
		<xs:attribute type="IntListType" name="npc_ids" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcGroup">
		<xs:attribute type="GroupDropType" name="group" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcGroups">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc_group" type="GlobalDropNpcGroup" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropZones">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_zone" type="GlobalDropZone" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropZone">
		<xs:attribute type="xs:string" name="zone" use="required" />
	</xs:complexType>

	<xs:simpleType name="StringFunction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONTAINS" />
			<xs:enumeration value="END_WITH" />
			<xs:enumeration value="START_WITH" />
			<xs:enumeration value="EQUALS" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RestrictionRace">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ASMODIANS" />
			<xs:enumeration value="ELYOS" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_dragon_lords_refuge.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Armor (Epic)" chance="75">
		<gd_maps>
			<gd_map map_id="300520000" /><!-- Dragon_Lords_Refuge -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="219359" /><!-- Calindi Flamelord -->
		</gd_npcs>
		<gd_items>
			<gd_item id="110101459" /><!-- Tiamat Guard's Tunic -->
			<gd_item id="113101334" /><!-- Tiamat Guard's Leggings -->
			<gd_item id="112101274" /><!-- Tiamat Guard's Pauldrons -->
			<gd_item id="111101317" /><!-- Tiamat Guard's Gloves -->
			<gd_item id="114101363" /><!-- Tiamat Guard's Shoes -->
			<gd_item id="110301369" /><!-- Tiamat Guard's Jerkin -->
			<gd_item id="113301336" /><!-- Tiamat Guard's Breeches -->
			<gd_item id="112301255" /><!-- Tiamat Guard's Shoulderguards -->
			<gd_item id="111301312" /><!-- Tiamat Guard's Vambrace -->
			<gd_item id="114301369" /><!-- Tiamat Guard's Boots -->
			<gd_item id="110501344" /><!-- Tiamat Guard's Hauberk -->
			<gd_item id="113501319" /><!-- Tiamat Guard's Chausses -->
			<gd_item id="112501244" /><!-- Tiamat Guard's Spaulders -->
			<gd_item id="111501304" /><!-- Tiamat Guard's Handguards -->
			<gd_item id="114501325" /><!-- Tiamat Guard's Brogans -->
			<gd_item id="110601317" /><!-- Tiamat Guard's Breastplate -->
			<gd_item id="113601271" /><!-- Tiamat Guard's Greaves -->
			<gd_item id="112601262" /><!-- Tiamat Guard's Shoulderplates -->
			<gd_item id="111601282" /><!-- Tiamat Guard's Gauntlets -->
			<gd_item id="114601266" /><!-- Tiamat Guard's Sabatons -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Supplements" chance="60">
		<gd_maps>
			<gd_map map_id="300520000" /><!-- Dragon_Lords_Refuge -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="219359" /><!-- Calindi Flamelord -->
		</gd_npcs>
		<gd_items>
			<gd_item id="166100011" min_count="10" max_count="20" /><!-- Greater Supplements (Mythic) -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_asteria_chamber.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Key" chance="75">
		<gd_maps>
			<gd_map map_id="300050000" /><!-- Asteria_Chamber -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214762" /><!-- Dakaer Chanter -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000033" /><!-- Golden Abyss Key -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="90">
		<gd_maps>
			<gd_map map_id="300050000" /><!-- Asteria_Chamber -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214766" /><!-- Dakaer Tactician -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000034" /><!-- Jeweled Abyss Key -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="300050000" /><!-- Asteria_Chamber -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="215444" /><!-- Ebonlord Kiriel -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000035" /><!-- Magic Abyss Key -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_raksang_ruins.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Reviver Nasto -->
	<gd_rule rule_name="Named Coins" chance="100">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236306" /><!-- Reviver Nasto -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000237" min_count="15" max_count="45" /><!-- Ancient Coin -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Weapon Box" chance="40">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236306" /><!-- Reviver Nasto -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053678" /><!-- Nasto's Unique Weapon Box -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor Box" chance="100">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236303" /><!-- Drill Instructor Diplito -->
			<gd_npc npc_id="236304" /><!-- Drill Instructor Pratica -->
			<gd_npc npc_id="236305" /><!-- Drill Instructor Exico -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053681" /><!-- Nasto's Unique Pauldrons Box -->
			<gd_item id="188053682" /><!-- Nasto's Unique Gloves Box -->
			<gd_item id="188053683" /><!-- Nasto's Unique Shoes Box -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor Box" chance="70">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236306" /><!-- Reviver Nasto -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053679" /><!-- Nasto's Unique Jacket Box -->
			<gd_item id="188053680" /><!-- Nasto's Unique Pants Box -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Accessory Box" chance="40">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236306" /><!-- Reviver Nasto -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053684" /><!-- Nasto's Hero Accessory Box -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Head" chance="70">
		<gd_maps>
			<gd_map map_id="300610000" /><!-- Raksang_Ruins -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="236306" /><!-- Reviver Nasto -->
		</gd_npcs>
		<gd_items>
			<gd_item id="125004215" /><!-- Nasto Legionnaire's Cloth Bandana -->
			<gd_item id="125004216" /><!-- Nasto Legionnaire's Leather Hat -->
			<gd_item id="125004217" /><!-- Nasto Legionnaire's Chain Helm -->
			<gd_item id="125004218" /><!-- Nasto Legionnaire's Plate Helmet -->
			<gd_item id="125004219" /><!-- Nasto Legionnaire's Leather Helmet -->
			<gd_item id="125004220" /><!-- Nasto Legionnaire's Chain Combat Helmet -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_shadow_court_dungeon.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<gd_rule rule_name="Named First Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214347" /><!-- Unfest Guard Captain -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000014" /><!-- Arena Basement Level 3 Key 1 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Second Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214349" /><!-- Dyspeptic Karnif -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000011" /><!-- Arena Basement Level 2 Key 1 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Third Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214351" /><!-- Dyspepsic Karnif -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000012" /><!-- Arena Basement Level 2 Key 2 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Fourth Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214353" /><!-- Bejeweled Mosbear -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000013" /><!-- Arena Basement Level 2 Key 3 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Fifth Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214530" /><!-- Prison Guard -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000008" /><!-- Arena Basement Level 1 Key 1 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Sixth Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214356" /><!-- Sorcerer Wraith -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000009" /><!-- Arena Basement Level 1 Key 2 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Seventh Key" chance="100">
		<gd_maps>
			<gd_map map_id="320120000" /><!-- Shadow_Court_Dungeon -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="214360" /><!-- Ranger Spirit -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000010" /><!-- Arena Basement Level 1 Key 3 -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_padmarashkas_cave.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Weapon (Epic)" chance="33">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="216580" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="100000920" /><!-- Padmarashka's Sword -->
			<gd_item id="100100690" /><!-- Padmarashka's Warhammer -->
			<gd_item id="100200820" /><!-- Padmarashka's Dagger -->
			<gd_item id="101700735" /><!-- Padmarashka's Longbow -->
			<gd_item id="100500711" /><!-- Padmarashka's Jewel -->
			<gd_item id="100600768" /><!-- Padmarashka's Tome -->
			<gd_item id="100900697" /><!-- Padmarashka's Greatsword -->
			<gd_item id="101300667" /><!-- Padmarashka's Spear -->
			<gd_item id="101500712" /><!-- Padmarashka's Staff -->
			<gd_item id="101800639" /><!-- Padmarashka's Pistol -->
			<gd_item id="101900638" /><!-- Padmarashka's Aethercannon -->
			<gd_item id="102100569" /><!-- Padmarashka's Cipher-Blade -->
			<gd_item id="102000673" /><!-- Padmarashka's Harp -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor (Unique)" chance="100">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="216580" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="110101090" /><!-- Padmarashka's Tunic -->
			<gd_item id="110301039" /><!-- Padmarashka's Jerkin -->
			<gd_item id="110501007" /><!-- Padmarashka's Hauberk -->
			<gd_item id="110600987" /><!-- Padmarashka's Breastplate -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor (Unique)" chance="100">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218756" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="110101090" /><!-- Padmarashka's Tunic -->
			<gd_item id="113100997" /><!-- Padmarashka's Leggings -->
			<gd_item id="112100941" /><!-- Padmarashka's Pauldrons -->
			<gd_item id="111100985" /><!-- Padmarashka's Gloves -->
			<gd_item id="114101026" /><!-- Padmarashka's Shoes -->
			<gd_item id="110301039" /><!-- Padmarashka's Jerkin -->
			<gd_item id="113301010" /><!-- Padmarashka's Breeches -->
			<gd_item id="112300939" /><!-- Padmarashka's Shoulderguards -->
			<gd_item id="111300990" /><!-- Padmarashka's Vambrace -->
			<gd_item id="114301046" /><!-- Padmarashka's Boots -->
			<gd_item id="110501007" /><!-- Padmarashka's Hauberk -->
			<gd_item id="113500980" /><!-- Padmarashka's Chausses -->
			<gd_item id="112500926" /><!-- Padmarashka's Spaulders -->
			<gd_item id="111500977" /><!-- Padmarashka's Handguards -->
			<gd_item id="114500989" /><!-- Padmarashka's Brogans -->
			<gd_item id="110600987" /><!-- Padmarashka's Breastplate -->
			<gd_item id="113600951" /><!-- Padmarashka's Greaves -->
			<gd_item id="112600941" /><!-- Padmarashka's Shoulderplates -->
			<gd_item id="111600968" /><!-- Padmarashka's Gauntlets -->
			<gd_item id="114600948" /><!-- Padmarashka's Sabatons -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Weapon (Epic)" chance="33">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218756" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="100000920" /><!-- Padmarashka's Sword -->
			<gd_item id="100100690" /><!-- Padmarashka's Warhammer -->
			<gd_item id="100200820" /><!-- Padmarashka's Dagger -->
			<gd_item id="101700735" /><!-- Padmarashka's Longbow -->
			<gd_item id="100500711" /><!-- Padmarashka's Jewel -->
			<gd_item id="100600768" /><!-- Padmarashka's Tome -->
			<gd_item id="100900697" /><!-- Padmarashka's Greatsword -->
			<gd_item id="101300667" /><!-- Padmarashka's Spear -->
			<gd_item id="101500712" /><!-- Padmarashka's Staff -->
			<gd_item id="101800639" /><!-- Padmarashka's Pistol -->
			<gd_item id="101900638" /><!-- Padmarashka's Aethercannon -->
			<gd_item id="102100569" /><!-- Padmarashka's Cipher-Blade -->
			<gd_item id="102000673" /><!-- Padmarashka's Harp -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Shield (Epic)" chance="33">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218756" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="115001332" /><!-- Padmarashka's Raging Scale Shield -->
			<gd_item id="115001017" /><!-- Padmarashka's Shield -->
			<gd_item id="115001325" /><!-- Padmarashka's Raging Shield -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor (Epic)" chance="33">
		<gd_maps>
			<gd_map map_id="320150000" /><!-- Padmarashkas_Cave -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218756" /><!-- Padmarashka -->
		</gd_npcs>
		<gd_items>
			<gd_item id="110101374" /><!-- Padmarashka's Raging Tunic -->
			<gd_item id="113101268" /><!-- Padmarashka's Raging Leggings -->
			<gd_item id="112101207" /><!-- Padmarashka's Raging Pauldrons -->
			<gd_item id="111101249" /><!-- Padmarashka's Raging Gloves -->
			<gd_item id="114101295" /><!-- Padmarashka's Raging Shoes -->
			<gd_item id="110301301" /><!-- Padmarashka's Raging Jerkin -->
			<gd_item id="113301270" /><!-- Padmarashka's Raging Breeches -->
			<gd_item id="112301190" /><!-- Padmarashka's Raging Shoulderguards -->
			<gd_item id="111301244" /><!-- Padmarashka's Raging Vambrace -->
			<gd_item id="114301301" /><!-- Padmarashka's Raging Boots -->
			<gd_item id="110301586" /><!-- Padmarashka's Magic Jerkin -->
			<gd_item id="113301552" /><!-- Padmarashka's Magic Breeches -->
			<gd_item id="112301465" /><!-- Padmarashka's Magic Shoulderguards -->
			<gd_item id="111301524" /><!-- Padmarashka's Magic Vambrace -->
			<gd_item id="114301590" /><!-- Padmarashka's Magic Boots -->
			<gd_item id="110501279" /><!-- Padmarashka's Raging Hauberk -->
			<gd_item id="113501255" /><!-- Padmarashka's Raging Chausses -->
			<gd_item id="112501183" /><!-- Padmarashka's Raging Spaulders -->
			<gd_item id="111501238" /><!-- Padmarashka's Raging Handguards -->
			<gd_item id="114501259" /><!-- Padmarashka's Raging Brogans -->
			<gd_item id="110551007" /><!-- Sensitive Padmarashka's Magic Hauberk -->
			<gd_item id="113501583" /><!-- Sensitive Padmarashka's Magic Chausses -->
			<gd_item id="112501507" /><!-- Sensitive Padmarashka's Magic Spaulders -->
			<gd_item id="111501565" /><!-- Sensitive Padmarashka's Magic Handguards -->
			<gd_item id="114501592" /><!-- Sensitive Padmarashka's Magic Brogans -->
			<gd_item id="110601252" /><!-- Padmarashka's Raging Breastplate -->
			<gd_item id="113601208" /><!-- Padmarashka's Raging Greaves -->
			<gd_item id="112601195" /><!-- Padmarashka's Raging Shoulderplates -->
			<gd_item id="111601217" /><!-- Padmarashka's Raging Gauntlets -->
			<gd_item id="114601201" /><!-- Padmarashka's Raging Sabatons -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_aetherogenetics_lab.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Multiple Monster Drops -->
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212174" /><!-- Librarian Selima -->
			<gd_npc npc_id="212175" /><!-- Expert Lab Scholar -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000002" /><!-- Lepharist Research Center Key 2 -->
		</gd_items>
	</gd_rule>
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Armor (Rare)" chance="70">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212174" /><!-- Librarian Selima -->
		</gd_npcs>
		<gd_items>
			<gd_item id="112100676" /><!-- Researcher's Pauldrons -->
			<gd_item id="112500664" /><!-- Researcher's Spaulders -->
			<gd_item id="114100745" /><!-- Researcher's Shoes -->
			<gd_item id="114300758" /><!-- Researcher's Boots -->
			<gd_item id="114500724" /><!-- Researcher's Brogans -->
			<gd_item id="114600684" /><!-- Researcher's Sabatons -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor (Rare)" chance="70">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212181" /><!-- Head Chef Pamsey -->
		</gd_npcs>
		<gd_items>
			<gd_item id="112300676" /><!-- Researcher's Shoulderguards -->
			<gd_item id="112600672" /><!-- Researcher's Shoulderplates -->
			<gd_item id="111100716" /><!-- Researcher's Gloves -->
			<gd_item id="111300718" /><!-- Researcher's Vambrace -->
			<gd_item id="111500705" /><!-- Researcher's Handguards -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Head (Rare)" chance="70">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212181" /><!-- Head Chef Pamsey -->
		</gd_npcs>
		<gd_items>
			<gd_item id="125001564" /><!-- Pamsey's Cooking Hat -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212193" /><!-- Pretor Key Keeper -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000004" /><!-- Lepharist Research Center Key 4 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212196" /><!-- Hungry Mudthorn -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000003" /><!-- Lepharist Research Center Key 3 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Weapon (Legend)" chance="30">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212211" /><!-- RM-78c -->
		</gd_npcs>
		<gd_items>
			<gd_item id="100000580" /><!-- Dominating Sword -->
			<gd_item id="100200554" /><!-- Dominating Dagger -->
			<gd_item id="100900439" /><!-- Dominating Greatsword -->
			<gd_item id="100500442" /><!-- Dominating Jewel -->
			<gd_item id="101700458" /><!-- Dominating Longbow -->
			<gd_item id="101300429" /><!-- Dominating Spear -->
			<gd_item id="101500444" /><!-- Dominating Staff -->
			<gd_item id="100600475" /><!-- Dominating Tome -->
			<gd_item id="100100445" /><!-- Dominating Warhammer -->
			<gd_item id="101900813" /><!-- Complete Subject's Aethercannon -->
			<gd_item id="101800809" /><!-- Complete Subject's Pistol -->
			<gd_item id="102100708" /><!-- Complete Subject's Cipher-Blade -->
			<gd_item id="102000847" /><!-- Complete Subject's Harp -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Armor (Rare)" chance="70">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212211" /><!-- RM-78c -->
		</gd_npcs>
		<gd_items>
			<gd_item id="113100725" /><!-- Researcher's Leggings -->
			<gd_item id="113300741" /><!-- Researcher's Breeches -->
			<gd_item id="113500715" /><!-- Researcher's Chausses -->
			<gd_item id="113600689" /><!-- Researcher's Greaves -->
			<gd_item id="110100802" /><!-- Researcher's Tunic -->
			<gd_item id="110300758" /><!-- Researcher's Jerkin -->
			<gd_item id="110500735" /><!-- Researcher's Hauberk -->
			<gd_item id="110600723" /><!-- Researcher's Breastplate -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212341" /><!-- The Keykeeper -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000001" /><!-- Lepharist Research Center Key 1 -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="310050000" /><!-- Aetherogenetics_Lab -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="212342" /><!-- Key Eater -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000005" /><!-- Lepharist Research Center Key 5 -->
		</gd_items>
	</gd_rule>
</global_rules>
