=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/global_rules.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../npcs/npcs.xsd" />
	<xs:include schemaLocation="../world_maps.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />

	<xs:element name="global_rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_rule" type="GlobalRule" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="GlobalRule">
		<xs:all>
			<xs:element name="gd_items" type="GlobalDropItems" />
			<xs:element minOccurs="0" name="gd_worlds" type="GlobalDropWorlds" />
			<xs:element minOccurs="0" name="gd_races" type="GlobalDropRaces" />
			<xs:element minOccurs="0" name="gd_ratings" type="GlobalDropRatings" />
			<xs:element minOccurs="0" name="gd_maps" type="GlobalDropMaps" />
			<xs:element minOccurs="0" name="gd_tribes" type="GlobalDropTribes" />
			<xs:element minOccurs="0" name="gd_npcs" type="GlobalDropNpcs" />
			<xs:element minOccurs="0" name="gd_npc_names" type="GlobalDropNpcNames" />
			<xs:element minOccurs="0" name="gd_npc_groups" type="GlobalDropNpcGroups" />
			<xs:element minOccurs="0" name="gd_excluded_npcs" type="GlobalDropExcludedNpcs" />
			<xs:element minOccurs="0" name="gd_zones" type="GlobalDropZones" />
		</xs:all>
		<xs:attribute name="rule_name" type="xs:string" use="required" />
		<xs:attribute name="chance" type="xs:float" use="required" />
		<xs:attribute name="dynamic_chance" type="xs:boolean" default="false" />
		<xs:attribute name="min_diff" type="xs:int" default="-99" />
		<xs:attribute name="max_diff" type="xs:int" default="99" />
		<xs:attribute name="restriction_race" type="RestrictionRace" />
		<xs:attribute name="level_based_chance_reduction" type="xs:boolean" default="false" />
		<xs:attribute name="member_limit" type="xs:int" default="1" />
		<xs:attribute name="max_drop_rule" type="xs:int" default="1" />
	</xs:complexType>

	<xs:complexType name="GlobalDropItems">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="gd_item" type="GlobalDropItem" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropItem">
		<xs:attribute type="xs:int" name="id" use="required" />
		<xs:attribute name="min_count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" />
		<xs:attribute type="xs:float" name="chance" default="100" />
	</xs:complexType>

	<xs:complexType name="GlobalDropWorlds">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_world" type="GlobalDropWorld" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropWorld">
		<xs:attribute type="worldDropType" name="wd_type" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropRaces">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_race" type="GlobalDropRace" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropRace">
		<xs:attribute type="Race" name="race" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropRatings">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_rating" type="GlobalDropRating" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropRating">
		<xs:attribute type="NpcRating" name="rating" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropMaps">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_map" type="GlobalDropMap" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropMap">
		<xs:attribute type="xs:int" name="map_id" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropTribes">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_tribe" type="GlobalDropTribe" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropTribe">
		<xs:attribute type="TribeClass" name="tribe" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcs">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc" type="GlobalDropNpc" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropNpc">
		<xs:attribute type="xs:int" name="npc_id" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcNames">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc_name" type="GlobalDropNpcName" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcName">
		<xs:attribute type="xs:string" name="value" use="required" />
		<xs:attribute type="StringFunction" name="function" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropExcludedNpcs">
		<xs:attribute type="IntListType" name="npc_ids" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcGroup">
		<xs:attribute type="GroupDropType" name="group" use="required" />
	</xs:complexType>

	<xs:complexType name="GlobalDropNpcGroups">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_npc_group" type="GlobalDropNpcGroup" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropZones">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="gd_zone" type="GlobalDropZone" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GlobalDropZone">
		<xs:attribute type="xs:string" name="zone" use="required" />
	</xs:complexType>

	<xs:simpleType name="StringFunction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONTAINS" />
			<xs:enumeration value="END_WITH" />
			<xs:enumeration value="START_WITH" />
			<xs:enumeration value="EQUALS" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RestrictionRace">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ASMODIANS" />
			<xs:enumeration value="ELYOS" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_the_eternal_bastion.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<gd_rule rule_name="Mobile Turret Key" chance="100">
		<gd_maps>
			<gd_map map_id="300540000" /><!-- The_Eternal_Bastion -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="230753" /><!-- Pashid Assault Rider -->
			<gd_npc npc_id="230757" /><!-- Pashid Assault Dragon -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000137" /><!-- Mobile Turret Key -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Balaur Supply Box" chance="100">
		<gd_maps>
			<gd_map map_id="300540000" /><!-- The_Eternal_Bastion -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="230753" /><!-- Pashid Assault Rider -->
			<gd_npc npc_id="230757" /><!-- Pashid Assault Dragon -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188052600" /><!-- Balaur Supply Box -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/rules_riftguards.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../global_rules.xsd">
	<gd_rule rule_name="RIFT_GUARD_MAJOR_AP_POTION" chance="40">
		<gd_npcs>
			<gd_npc npc_id="209518" /><!-- Eltnen Sentinel -->
			<gd_npc npc_id="209519" /><!-- Heiron Protector -->
			<gd_npc npc_id="209520" /><!-- Inggison Sentinel -->
			<gd_npc npc_id="209521" /><!-- Morheim Protector -->
			<gd_npc npc_id="209522" /><!-- Beluslan Protector -->
			<gd_npc npc_id="209523" /><!-- Gelkmaros Protector -->
			<gd_npc npc_id="209524" /><!-- Eltnen Elite Templar -->
			<gd_npc npc_id="209525" /><!-- Eltnen Elite Gladiator -->
			<gd_npc npc_id="209526" /><!-- Eltnen Elite Ranger -->
			<gd_npc npc_id="209527" /><!-- Eltnen Elite Sorcerer -->
			<gd_npc npc_id="209528" /><!-- Eltnen Elite Cleric -->
			<gd_npc npc_id="209529" /><!-- Heiron Elite Templar -->
			<gd_npc npc_id="209530" /><!-- Heiron Elite Gladiator -->
			<gd_npc npc_id="209531" /><!-- Heiron Elite Marksman -->
			<gd_npc npc_id="209532" /><!-- Heiron Elite Sorcerer -->
			<gd_npc npc_id="209533" /><!-- Heiron Elite Cleric -->
			<gd_npc npc_id="209534" /><!-- Inggison Elite Templar -->
			<gd_npc npc_id="209535" /><!-- Inggison Elite Gladiator -->
			<gd_npc npc_id="209536" /><!-- Inggison Elite Ranger -->
			<gd_npc npc_id="209537" /><!-- Inggison Elite Sorcerer -->
			<gd_npc npc_id="209538" /><!-- Inggison Elite Cleric -->
			<gd_npc npc_id="209539" /><!-- Morheim Elite Templar -->
			<gd_npc npc_id="209540" /><!-- Morheim Elite Gladiator -->
			<gd_npc npc_id="209541" /><!-- Morheim Elite Ranger -->
			<gd_npc npc_id="209542" /><!-- Morheim Elite Sorcerer -->
			<gd_npc npc_id="209543" /><!-- Morheim Elite Cleric -->
			<gd_npc npc_id="209544" /><!-- Beluslan Elite Templar -->
			<gd_npc npc_id="209545" /><!-- Beluslan Elite Gladiator -->
			<gd_npc npc_id="209546" /><!-- Beluslan Elite Ranger -->
			<gd_npc npc_id="209547" /><!-- Beluslan Elite Sorcerer -->
			<gd_npc npc_id="209548" /><!-- Beluslan Elite Cleric -->
			<gd_npc npc_id="209549" /><!-- Gelkmaros Elite Templar -->
			<gd_npc npc_id="209550" /><!-- Gelkmaros Elite Gladiator -->
			<gd_npc npc_id="209551" /><!-- Gelkmaros Elite Ranger -->
			<gd_npc npc_id="209552" /><!-- Gelkmaros Elite Sorcerer -->
			<gd_npc npc_id="209553" /><!-- Gelkmaros Elite Cleric -->
		</gd_npcs>
		<gd_items>
			<gd_item id="162000069" /><!-- Major Divine Life Serum -->
			<gd_item id="162000070" /><!-- Major Divine Mana Serum -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="RIFT_GUARD_RELICS" chance="40">
		<gd_npcs>
			<gd_npc npc_id="209518" /><!-- Eltnen Sentinel -->
			<gd_npc npc_id="209519" /><!-- Heiron Protector -->
			<gd_npc npc_id="209520" /><!-- Inggison Sentinel -->
			<gd_npc npc_id="209521" /><!-- Morheim Protector -->
			<gd_npc npc_id="209522" /><!-- Beluslan Protector -->
			<gd_npc npc_id="209523" /><!-- Gelkmaros Protector -->
			<gd_npc npc_id="209524" /><!-- Eltnen Elite Templar -->
			<gd_npc npc_id="209525" /><!-- Eltnen Elite Gladiator -->
			<gd_npc npc_id="209526" /><!-- Eltnen Elite Ranger -->
			<gd_npc npc_id="209527" /><!-- Eltnen Elite Sorcerer -->
			<gd_npc npc_id="209528" /><!-- Eltnen Elite Cleric -->
			<gd_npc npc_id="209529" /><!-- Heiron Elite Templar -->
			<gd_npc npc_id="209530" /><!-- Heiron Elite Gladiator -->
			<gd_npc npc_id="209531" /><!-- Heiron Elite Marksman -->
			<gd_npc npc_id="209532" /><!-- Heiron Elite Sorcerer -->
			<gd_npc npc_id="209533" /><!-- Heiron Elite Cleric -->
			<gd_npc npc_id="209534" /><!-- Inggison Elite Templar -->
			<gd_npc npc_id="209535" /><!-- Inggison Elite Gladiator -->
			<gd_npc npc_id="209536" /><!-- Inggison Elite Ranger -->
			<gd_npc npc_id="209537" /><!-- Inggison Elite Sorcerer -->
			<gd_npc npc_id="209538" /><!-- Inggison Elite Cleric -->
			<gd_npc npc_id="209539" /><!-- Morheim Elite Templar -->
			<gd_npc npc_id="209540" /><!-- Morheim Elite Gladiator -->
			<gd_npc npc_id="209541" /><!-- Morheim Elite Ranger -->
			<gd_npc npc_id="209542" /><!-- Morheim Elite Sorcerer -->
			<gd_npc npc_id="209543" /><!-- Morheim Elite Cleric -->
			<gd_npc npc_id="209544" /><!-- Beluslan Elite Templar -->
			<gd_npc npc_id="209545" /><!-- Beluslan Elite Gladiator -->
			<gd_npc npc_id="209546" /><!-- Beluslan Elite Ranger -->
			<gd_npc npc_id="209547" /><!-- Beluslan Elite Sorcerer -->
			<gd_npc npc_id="209548" /><!-- Beluslan Elite Cleric -->
			<gd_npc npc_id="209549" /><!-- Gelkmaros Elite Templar -->
			<gd_npc npc_id="209550" /><!-- Gelkmaros Elite Gladiator -->
			<gd_npc npc_id="209551" /><!-- Gelkmaros Elite Ranger -->
			<gd_npc npc_id="209552" /><!-- Gelkmaros Elite Sorcerer -->
			<gd_npc npc_id="209553" /><!-- Gelkmaros Elite Cleric -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000051" /><!-- Major Ancient Crown -->
			<gd_item id="186000052" /><!-- Greater Ancient Crown -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="RIFT_GUARD_MEDAL" chance="35">
		<gd_npcs>
			<gd_npc npc_id="209518" /><!-- Eltnen Sentinel -->
			<gd_npc npc_id="209519" /><!-- Heiron Protector -->
			<gd_npc npc_id="209520" /><!-- Inggison Sentinel -->
			<gd_npc npc_id="209521" /><!-- Morheim Protector -->
			<gd_npc npc_id="209522" /><!-- Beluslan Protector -->
			<gd_npc npc_id="209523" /><!-- Gelkmaros Protector -->
			<gd_npc npc_id="209524" /><!-- Eltnen Elite Templar -->
			<gd_npc npc_id="209525" /><!-- Eltnen Elite Gladiator -->
			<gd_npc npc_id="209526" /><!-- Eltnen Elite Ranger -->
			<gd_npc npc_id="209527" /><!-- Eltnen Elite Sorcerer -->
			<gd_npc npc_id="209528" /><!-- Eltnen Elite Cleric -->
			<gd_npc npc_id="209529" /><!-- Heiron Elite Templar -->
			<gd_npc npc_id="209530" /><!-- Heiron Elite Gladiator -->
			<gd_npc npc_id="209531" /><!-- Heiron Elite Marksman -->
			<gd_npc npc_id="209532" /><!-- Heiron Elite Sorcerer -->
			<gd_npc npc_id="209533" /><!-- Heiron Elite Cleric -->
			<gd_npc npc_id="209534" /><!-- Inggison Elite Templar -->
			<gd_npc npc_id="209535" /><!-- Inggison Elite Gladiator -->
			<gd_npc npc_id="209536" /><!-- Inggison Elite Ranger -->
			<gd_npc npc_id="209537" /><!-- Inggison Elite Sorcerer -->
			<gd_npc npc_id="209538" /><!-- Inggison Elite Cleric -->
			<gd_npc npc_id="209539" /><!-- Morheim Elite Templar -->
			<gd_npc npc_id="209540" /><!-- Morheim Elite Gladiator -->
			<gd_npc npc_id="209541" /><!-- Morheim Elite Ranger -->
			<gd_npc npc_id="209542" /><!-- Morheim Elite Sorcerer -->
			<gd_npc npc_id="209543" /><!-- Morheim Elite Cleric -->
			<gd_npc npc_id="209544" /><!-- Beluslan Elite Templar -->
			<gd_npc npc_id="209545" /><!-- Beluslan Elite Gladiator -->
			<gd_npc npc_id="209546" /><!-- Beluslan Elite Ranger -->
			<gd_npc npc_id="209547" /><!-- Beluslan Elite Sorcerer -->
			<gd_npc npc_id="209548" /><!-- Beluslan Elite Cleric -->
			<gd_npc npc_id="209549" /><!-- Gelkmaros Elite Templar -->
			<gd_npc npc_id="209550" /><!-- Gelkmaros Elite Gladiator -->
			<gd_npc npc_id="209551" /><!-- Gelkmaros Elite Ranger -->
			<gd_npc npc_id="209552" /><!-- Gelkmaros Elite Sorcerer -->
			<gd_npc npc_id="209553" /><!-- Gelkmaros Elite Cleric -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000147" /><!-- Mithril Medal -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Boss Volatile Bundle" chance="100" member_limit="18">
		<gd_npcs>
			<gd_npc npc_id="219887" /><!-- Captain Brimas -->
			<gd_npc npc_id="219906" /><!-- Captain Meriward  -->
			<gd_npc npc_id="219913" /><!-- Captaim Roblick -->
			<gd_npc npc_id="236035" /><!-- Third Ironlightian Deity General -->
			<gd_npc npc_id="236048" /><!-- Sixth Ironlightian Deity General -->
			<gd_npc npc_id="236055" /><!-- Seventh Ironlightian Deity General -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053717" /><!-- Volatile Rift Victory Loot Bundle -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Volatile Bundle" chance="100" member_limit="3">
		<gd_npcs>
			<gd_npc npc_id="235830" /><!-- Mutated Gatorback Skilex -->
			<gd_npc npc_id="235832" /><!-- Aggressive Coral Corask  -->
			<gd_npc npc_id="235918" /><!-- Frostshard Kirrin -->
			<gd_npc npc_id="235916" /><!-- Freezing Petrahulk -->
			<gd_npc npc_id="235912" /><!-- Stygian Mist Warrior -->
			<gd_npc npc_id="235914" /><!-- Stygian Mist Protector -->
			<gd_npc npc_id="219699" /><!-- Flameskin Cellatu -->
			<gd_npc npc_id="219700" /><!-- Frenzied Skyray -->
			<gd_npc npc_id="219776" /><!-- Awoken Jotun Worker -->
			<gd_npc npc_id="219777" /><!-- Awoken Jotun Craftsman -->
			<gd_npc npc_id="219787" /><!-- Frenzied Darksea Spiner -->
			<gd_npc npc_id="219788" /><!-- Primeval Sea Giant -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053716" /><!-- Volatile Rift Loot Bundle -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_kysis_barracks.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Multiple Monster Drops -->
	<gd_rule rule_name="Named Key" chance="100">
		<gd_maps>
			<gd_map map_id="301240000" /><!-- Legion_Kysis_Barracks -->
			<gd_map map_id="301280000" /><!-- Kysis_Barracks -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233670" /><!-- Treasurer Darmaraja -->
			<gd_npc npc_id="233671" /><!-- Treasurer Swaraja -->
			<gd_npc npc_id="233672" /><!-- Treasurer Chandra -->
			<gd_npc npc_id="233673" /><!-- Treasurer Dragagh -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000061" /><!-- Kysis Armory Key -->
			<gd_item id="185000062" /><!-- Kysis Supply Base Key -->
			<gd_item id="185000063" /><!-- Kysis Operations Room Key -->
		</gd_items>
	</gd_rule>
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Mark" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="301240000" /><!-- Legion_Kysis_Barracks -->
			<gd_map map_id="301280000" /><!-- Kysis_Barracks -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233675" /><!-- Weakened Kysis Duke -->
			<gd_npc npc_id="233676" /><!-- Enraged Kysis Duke -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000238" min_count="60" max_count="90" /><!-- Conqueror's Mark -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Treasure Key" chance="100">
		<gd_maps>
			<gd_map map_id="301240000" /><!-- Legion_Kysis_Barracks -->
			<gd_map map_id="301280000" /><!-- Kysis_Barracks -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233675" /><!-- Weakened Kysis Duke -->
			<gd_npc npc_id="233676" /><!-- Enraged Kysis Duke -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000064" /><!-- Kysis Treasure Room Key -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Gold Key" chance="100">
		<gd_maps>
			<gd_map map_id="301240000" /><!-- Legion_Kysis_Barracks -->
			<gd_map map_id="301280000" /><!-- Kysis_Barracks -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233675" /><!-- Weakened Kysis Duke -->
			<gd_npc npc_id="233676" /><!-- Enraged Kysis Duke -->
		</gd_npcs>
		<gd_items>
			<gd_item id="185000065" /><!-- Kysis Gold Room Key -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/rules_sandstorm_targets.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../global_rules.xsd">
	<gd_rule rule_name="Kahruns Symbol" chance="100" member_limit="4">
		<gd_npcs>
			<gd_npc npc_id="218543" /><!-- Assault Team Leader Kunati -->
			<gd_npc npc_id="218459" /><!-- Brigade General Satra -->
			<gd_npc npc_id="218518" /><!-- Colossal Geodenos -->
			<gd_npc npc_id="218078" /><!-- Nemeco the Dancer -->
			<gd_npc npc_id="218493" /><!-- Merciless Lamaz -->
			<gd_npc npc_id="218555" /><!-- Aide Iranati -->
			<gd_npc npc_id="218557" /><!-- Master-at-Arms Ranigan -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000143" min_count="30" max_count="40" /><!-- Kahrun's Symbol -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Kahruns Symbol" chance="100" member_limit="6">
		<gd_npcs>
			<gd_npc npc_id="218495" /><!-- Chieftain Pukikor -->
			<gd_npc npc_id="218519" /><!-- Yndigo Blackice -->
			<gd_npc npc_id="218082" /><!-- Daturum Wreckhelm -->
			<gd_npc npc_id="218080" /><!-- Nubale the Glacier -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000143" min_count="60" max_count="90" /><!-- Kahrun's Symbol -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Kahruns Symbol" chance="100" member_limit="8">
		<gd_npcs>
			<gd_npc npc_id="217964" /><!-- Deputy Chieftain Aruru -->
			<gd_npc npc_id="218745" /><!-- Ruthless Ossek -->
			<gd_npc npc_id="218540" /><!-- Flaming Breath Byak -->
			<gd_npc npc_id="218247" /><!-- Cavalry Chief Tagata -->
			<gd_npc npc_id="218005" /><!-- Chieftain Haridoo -->
			<gd_npc npc_id="218326" /><!-- Continuum Guardian Arachi -->
			<gd_npc npc_id="218004" /><!-- Chaburat the Noble -->
			<gd_npc npc_id="218085" /><!-- Debarim the Omnipotent -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000143" min_count="135" max_count="180" /><!-- Kahrun's Symbol -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/open_worlds/rules_map_oriel.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Multiple Monster Drops -->
	<gd_rule rule_name="Named Mount" chance="20">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218850"/><!-- Spring Agrint -->
			<gd_npc npc_id="218851"/><!-- Summer Agrint -->
			<gd_npc npc_id="218852"/><!-- Autumn Agrint -->
			<gd_npc npc_id="218853"/><!-- Winter Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="190100012"/><!-- Waveform Surfrider -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Bundle" chance="100">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218850"/><!-- Spring Agrint -->
			<gd_npc npc_id="218851"/><!-- Summer Agrint -->
			<gd_npc npc_id="218852"/><!-- Autumn Agrint -->
			<gd_npc npc_id="218853"/><!-- Winter Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188051564" max_count="2"/><!-- Housing Accessory Bundle -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Light" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218850"/><!-- Spring Agrint -->
			<gd_npc npc_id="218851"/><!-- Summer Agrint -->
			<gd_npc npc_id="218852"/><!-- Autumn Agrint -->
			<gd_npc npc_id="218853"/><!-- Winter Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006984"/><!-- Season's Light -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Aether Gem" chance="80">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218854"/><!-- Vernal Audria -->
			<gd_npc npc_id="218855"/><!-- Sprouting Audria -->
			<gd_npc npc_id="218856"/><!-- Sweltering Audria -->
			<gd_npc npc_id="218857"/><!-- Rain Audria -->
			<gd_npc npc_id="218858"/><!-- Foliage Audria -->
			<gd_npc npc_id="218859"/><!-- Sunset Audria -->
			<gd_npc npc_id="218860"/><!-- Ice Audria -->
			<gd_npc npc_id="218861"/><!-- Snowflower Audria -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006851"/><!-- Broken Aether Gem -->
			<gd_item id="182006852"/><!-- Rough Aether Gem -->
			<gd_item id="182006853"/><!-- Hard Aether Gem -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Fertile Soil" chance="100">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218854"/><!-- Vernal Audria -->
			<gd_npc npc_id="218855"/><!-- Sprouting Audria -->
			<gd_npc npc_id="218856"/><!-- Sweltering Audria -->
			<gd_npc npc_id="218857"/><!-- Rain Audria -->
			<gd_npc npc_id="218858"/><!-- Foliage Audria -->
			<gd_npc npc_id="218859"/><!-- Sunset Audria -->
			<gd_npc npc_id="218860"/><!-- Ice Audria -->
			<gd_npc npc_id="218861"/><!-- Snowflower Audria -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006981"/><!-- Divine Fertile Soil -->
		</gd_items>
	</gd_rule>
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Season Crystal" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218850"/><!-- Spring Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006839" max_count="3"/><!-- Spring Crystal -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Crystal" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218851"/><!-- Summer Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006840" max_count="3"/><!-- Summer Crystal -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Crystal" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218852"/><!-- Autumn Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006841" max_count="3"/><!-- Fall Crystal -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Crystal" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218853"/><!-- Winter Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006842" max_count="3"/><!-- Winter Crystal -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Leaf" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218850"/><!-- Spring Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006843"/><!-- Spring Leaf -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Leaf" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218851"/><!-- Summer Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006844"/><!-- Summer Leaf -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Leaf" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218852"/><!-- Autumn Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006845"/><!-- Autumn Leaf -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Season Leaf" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="700010000"/><!-- Oriel -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="218853"/><!-- Winter Agrint -->
		</gd_npcs>
		<gd_items>
			<gd_item id="182006846"/><!-- Winter Leaf -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/open_worlds/rules_map_transidium_annex.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<gd_rule rule_name="Name Box" chance="100" member_limit="100">
		<gd_maps>
			<gd_map map_id="400030000" /><!-- Transidium_Annex -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="277224" /><!-- Ahserion -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188053117" /><!-- Ahserion's Glory Reward Box -->
		</gd_items>
	</gd_rule>
</global_rules>

=== dissaramdhani/Aion4.8/game-server/data/static_data/global_drops/rules/instances/rules_map_illuminary_obelisk.xml
<?xml version="1.0" encoding="utf-8"?>
<global_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../global_rules.xsd">
	<!-- Single Monster Drops -->
	<gd_rule rule_name="Named Mark" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="186000238" min_count="60" max_count="90" /><!-- Conqueror's Mark -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Idian Pouch" chance="100">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188052825" /><!-- Illuminary Obelisk Idian Pouch -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Supply Chest" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188052823" /><!-- Illuminary Obelisk Supply Chest -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Equipment Chest" chance="100" member_limit="6">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188052827" /><!-- Dynatoum's Equipment Chest -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Enhancement Chest" chance="40">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="188052824" /><!-- Illuminary Obelisk Enhancement Box -->
		</gd_items>
	</gd_rule>
	<gd_rule rule_name="Named Wings" chance="20">
		<gd_maps>
			<gd_map map_id="301230000" /><!-- Illuminary_Obelisk -->
		</gd_maps>
		<gd_npcs>
			<gd_npc npc_id="233740" /><!-- Test Weapon Dynatoum -->
		</gd_npcs>
		<gd_items>
			<gd_item id="187000129" chance="30" /><!-- Brazen Bulwark Burster -->
			<gd_item id="187000130" chance="70" /><!-- Bulwark Burster -->
		</gd_items>
	</gd_rule>
</global_rules>
